genshinsim/gcsim

- internal/characters/noelle/noelle.go
fix 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x655598]
goroutine 22 [running]:
github.com/genshinsim/gsim/internal/characters/noelle.(*noelleShield).OnExpire(0xc000190200)
C:/HOME/Projects/gsim/internal/characters/noelle/noelle.go:166 +0x18
github.com/genshinsim/gsim/pkg/core.(*ShieldCtrl).Tick(0xc00019c140)
C:/HOME/Projects/gsim/pkg/core/shield.go:118 +0x12b
github.com/genshinsim/gsim/pkg/core.(*Core).Tick(0xc0001ac000)
C:/HOME/Projects/gsim/pkg/core/core.go:269 +0x56
github.com/genshinsim/gsim.(*Simulation).AdvanceFrame(0xc0001aa000)
C:/HOME/Projects/gsim/run.go:67 +0x3a
github.com/genshinsim/gsim.(*Simulation).Run(0xc0001aa000)
C:/HOME/Projects/gsim/run.go:40 +0x396 …
```
> fix noelle shield

- internal/weapons/sword/lion/lion.go
Lion's roar was checking for Electro/Hydro and not Electro/Pyro.
> Fix Lion's Roar passive to check for correct elements

- internal/characters/kazuha/abil.go
Temporary hack for Bennett Q and Kazuha Q infusion. I think this is mostly only important for Kazuha vs. other anemo characters because with how his E/Q work he's guaranteed to pick up the infusion and it ends up being a crucial part of how many teams work (Melt Ganyu Kazuha, Childe Reverse Vape Kazuha, Raiden Hyper, etc.)
> Implement temporary hack for Bennett Q pyro infusion for Kazuha

- internal/characters/bennett/bennett.go
- internal/characters/raiden/abil.go
- internal/characters/xingqiu/burst.go
- internal/characters/xingqiu/xingqiu.go
- pkg/character/tasks.go
This PR starts the process for adjusting snapshot timings (partially fixes #31) and implements the following fixes:
1. Adds a helper function in the core to align the snapshot generation and damage instance
2. Fixes the timings for Raiden, XQ, and Bennett who are all known to have fully dynamic abilities.
> Adjust snapshot timings - Core, Raiden, XQ, Bennett

- internal/characters/albedo/albedo.go
- internal/characters/hutao/hutao.go
- internal/characters/sara/abil.go
- internal/characters/xiangling/xiangling.go
- internal/weapons/catalyst/prototype/prototype.go
Fixes:
- Albedo E did not target all enemies
- Hu Tao E duration was wrong
- Sara E/C2 had incorrect ICD
- XL C2 was not handled correctly
- Prototype Amber energy recovery was applying to all characters rather than
weapon holder
> Bugfixes: Albedo E, Hu Tao E, Sara E/C2 ICD, XL C2, Prototype Amber

- internal/characters/eula/eula.go
Change Eula constellation 2 to reduce the CD of hold E rather than reduce the cast animation of hold E.
> Fix Eula Constellation 2 CD Reduction

- internal/characters/klee/klee.go
- internal/characters/zhongli/abil.go
- internal/characters/zhongli/construct.go
- internal/characters/zhongli/stele.go
- internal/characters/zhongli/zhongli.go
- pkg/monster/cryo.go
- pkg/monster/electro.go
- pkg/monster/hydro.go
- pkg/monster/pyro.go
Fixes:
- OnReactionOccured event was firing when aura was being refreshed
- Klee 3rd bounce was not 2B durability (fixes #39)
- Changed all instances of "Steele" to "Stele" in Zhongli code
- Fixed Zhongli stele spawn not procing damage (fixes #56)
- Fixed incorrect Zhongli stele and shield spawn frames
> Various Bugfixes: OnReactionOccured event proc, Klee E, Zhongli

- internal/characters/beidou/abil.go
- internal/characters/diona/abil.go
- internal/characters/kaeya/cons.go
- internal/characters/noelle/abil.go
- internal/characters/noelle/noelle.go
- internal/characters/yanfei/abil.go
- internal/characters/yoimiya/abil.go
- internal/characters/zhongli/shield.go
- internal/weapons/claymore/bell/bell.go
- pkg/character/actions.go
- pkg/character/tmpl.go
- pkg/core/construct.go
- pkg/core/events.go
- pkg/core/shield.go
- pkg/core/stam.go
- pkg/core/target/mods.go
- pkg/reactable/crystallize.go
- Yoimiya A4 did not activate properly
- Shield names all added
- Zhongli Shield Type fixed to Geo
- Unified array checking interface where we need to replace existing entries
- Fixes issues like Zhongli E shield not refreshing properly (Closes #150)
> Fixes: Yoimiya A4, Shield Names, Zhongli Shield Type, Array Checks

- internal/characters/barbara/abil.go
- internal/characters/bennett/bennett.go
- internal/characters/gorou/abil.go
- internal/characters/shenhe/abil.go
- internal/characters/yunjin/abil.go
- internal/weapons/claymore/redhorn/redhorn.go
- internal/weapons/sword/cinnabar/cinnnabar.go
- pkg/character/stats.go
- pkg/core/action.go
- pkg/core/attackevent.go
- pkg/core/combat.go
- pkg/core/target/attack.go
Streamlines the log display so things are more readable primarily by condensing the various snapshot debug logs into the damage log, making the debug view much faster to parse as you don't need to go scrolling around for the frame on which skills were snapshot to see their mods, and also exposes resist mods without needing to go into the Calc log.
I did not make changes related to flat damage logging (e.g., Yun Jin), so those still live in "Pre Damage Mods". As a result, I've disabled the old pre-damage mods view since those on the same frame as the damage log anyway, but the old "Snapshot_Mods" view still exist even though it's now mostly duplicative with the new damage log view in case it's useful.
Before:
After:
New damage log view:
> Logging improvements

- internal/characters/kokomi/abil.go
- internal/characters/kokomi/kokomi.go
- internal/weapons/catalyst/prototype/prototype.go
- Fix bonus from Kokomi's A4;
- Fix heal bonus from Kokomi's skill/burst;
- Fix heal bonus from passive of Prototype Amber;
> Fixes / Kokomi's A4/Skill/Burst & Prototype Amber

- internal/artifacts/paleflame/paleflame.go
- internal/characters/bennett/bennett.go
- internal/characters/gorou/cons.go
- pkg/character/energy.go
- Fixes pale flame 2 pc set typo
- Fixes Bennett burst frame timing and A4 activation method
- Fixes Gorou C6 incorrectly snapshotting
- Add max energy in energy log
> Bugfixes - Pale Flame, Bennett Burst and A4, Gorou C6, Energy Log

- internal/characters/keqing/abil.go
- internal/characters/shenhe/abil.go
- internal/reactable/crystallize.go
- internal/substatoptimizer/substatoptimizer.go
- internal/tmpl/character/energy.go
- internal/tmpl/status/status.go
- pkg/simulation/energy.go
Fixes #272 and #273 - Shenhe particle timing and burst
- Burst ticks were incorrectly coded
- C2 was not implemented correctly
- Burst res shred duration was wrong
Fixes #235 - Generated crystallize shields were always electro
Fixes #284 and #285 - Add particles to Keqing E; fix Keqing Q name
Fixes #286 - Substat optimizer should ignore gzip setting
Fixes #288 - Updates log for energy add, random normals, and status
> Bugfixes - Shenhe, Crystallize, Keqing E and Q, Substat Optimizer, Log Improvements

- internal/characters/yaemiko/yaemiko.go
fixes #332 
test config: https://gcsim.app/viewer/share/NzAud0AZxqV_otlG-JWEu
status duration is 900, set to attack only if expiry < 500, attack starts at frame 401 as expected
> change yae totem status to oldest_totem_expiry

- internal/tmpl/character/mods.go
- internal/tmpl/character/tmpl.go
- internal/tmpl/status/status.go
- internal/tmpl/target/mods.go
- pkg/core/character.go
- pkg/core/target.go
this should let you click on mods for charstat, predamagemod, enemy res and def mod and see the duration
only issue is that refresh only shows the duration of that refresh but if you want to see the entire time that the buff is active you gotta find the original added...
> add ended status tracking for mods

- cmd/gcsim/.gitignore
- internal/characters/kazuha/abil.go
- internal/characters/kazuha/frames.go
- internal/characters/kazuha/kazuha.go
- internal/tmpl/action/action.go
- internal/tmpl/character/actions.go
- internal/tmpl/character/frames.go
- internal/tmpl/character/tmpl.go
- pkg/core/action.go
- pkg/core/cfg.go
- pkg/core/character.go
- pkg/core/core.go
- pkg/parse/parseOptions.go
- pkg/simulation/core.go
- pkg/simulation/run.go
- pkg/simulation/sim.go
fixes #267 
@Tsym-or-Tysm this one probably need extensive testing
I tested with the following config and it works fine but I'm not overly confident on the logic especially on `/pkg/simulation/run.go` L114
```
options debug=true iteration=1 duration=90 workers=24 mode=apl attack_delay=100 skill_delay=100;
bennett char lvl=90/90 cons=5 talent=9,9,9; 
bennett add weapon="aquilafavonia" refine=1 lvl=90/90;
##Default Enemy
target lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
active bennett;
bennett attack;
```
> custom global delay, frames framework, kazuha frame update

- internal/characters/beidou/abil.go
Fix issue with Beidou Q proc'ing on normals that hit after char is already no longer on field
> fix beidou q proc'ing off-field

- internal/weapons/common/common.go
- internal/weapons/sword/darkironsword/darkironsword.go
- internal/weapons/sword/silversword/silversword.go
- internal/weapons/sword/swordofdescension/swordofdescension.go
- internal/weapons/sword/travelershandysword/travelershandysword.go
- pkg/simulation/imports.go
* Implements darkironsword, silversword, swordofdescension, travelershandysword
* Add common.NoEffectWeapon(string) for weapons that are primarily stat sticks and offer no meaningful weapon effect for the sim.
* Add simple tests for the weapon effects.
Weapon tests;
* Traveler's Handy Sword Heals - https://gcsim.app/viewer/share/perm_UsWjYrLkVo-1ajtzWtSwX
* Sword of Descension Attack Procs & Buff Applies to Trav - https://gcsim.app/viewer/share/perm_7Sx-jirFSYoOTe2oBeffX
* Dark Iron Sword procs on superconduct, overload, electrocharge - https://gcsim.app/viewer/share/perm_ZvZcdhrcAHJ6AzqgQgT93
> Add remaining swords

- internal/characters/raiden/abil.go
Raiden E now procs on reaction damage, except for Hydro Swirl and EC.
> Issue 435 raiden e proc on reaction

- internal/artifacts/echoes/echoes.go
echoes shouldn't be calling snapshot again
> fix echoes and yoi interaction

- internal/characters/zhongli/stele.go
zhongli steles should only make an extra tick for each extra non-stele construct.
> zhongli stele tick fix

- internal/characters/yoimiya/abil.go
- internal/characters/yoimiya/yoimiya.go
* Previously Yoi's snapshot routine was apply the effect of her skill multiplier. This was causing additional talent multiplier in the calculation of her damage when multiple snapshots are made of the same attack.
> Move Yoimiya's skill buff effect

- internal/substatoptimizer/substatoptimizer.go
In some configs the substat optimizer fails to give Favonius weapon users enough CR. This fix increases the gradient for CR so that the optimizer picks it instead of ATK% (+1000 seemed like a good number because that makes CR usually end up being chosen after CD (gradient is usually > 1000) but before ATK% (gradient is usually < 1000).
The main reason for this fix is that EM/EM/EM Fav Kazuha sometimes gets max'd out ATK% subs instead of crit rate subs leading to less dps and a higher standard deviation.
> adjust substat optimizer to reliably give more cr to fav weapon users

- .github/workflows/nightly-build.yaml
Fix the issue with the latest release URL redirecting to nightly.
> Tag nightly builds as prerelease

- internal/reactable/freeze.go
Moved the onFreeze event emit to occur before the tryFreeze function returns.
> Fixes Instructors not proccing on freeze (Issue #546)

- cmd/wasm/main.go
Configs were not being cloned in wasm. This results in +limit=1 not working properly
> fix config not cloned

- cmd/gcsim/main.go
allow `gcsim.exe` local build to serve results directly (instead of having to drag and drop to viewer)
`gcsim.exe -s` to do so
> add ability to load result in browser automatically

- pkg/core/cfg.go
- pkg/parse/parseOptions.go
- pkg/simulation/characters.go
- pkg/simulation/run.go
Seems like there are some rounding errors from result/results.go, but they should just be aesthetic 
<https://gcsim.app/viewer/share/Y4LJSdYvATtgEURXvAsUS>
> Allow fractional durations

- internal/characters/itto/abil.go
Bugfixes:
1. Fixes Itto not recieving the last SSS stack from C1 when he already had 4.
2. Corrects the frames at which Itto recieves SSS stacks from C1.
3. Fixes Itto's NA combo not being reset by CAs.
> Fix itto C1 and NA counter not being reset by CA

- pkg/core/player/character/energy.go
Not sure if there's a particular reason why `pre_recovery` field is not included in the `energy` event emitted from `AddEnergy`, but if there isn't, here's a patch to add it. This makes it more consistent to the `energy` events emitted elsewhere.
Tested locally by inspecting the output data.
First time contributing here, so let me know if I missed anything. Thanks!
> Includes pre_recovery field in AddEnergy log entry

- internal/characters/kuki/cons.go
C4 now generates particles on each proc with a %45 chance of doing so.
Additionally the ICD tag changed to none, since it isn't shared with the skill
Disclaimer: This PR is NOT meant to be a bugfix, instead, it's a feature addition, so please treat is as such
> Kuki feature update

- .gitignore
- cmd/gcsim/main.go
- pkg/core/core.go
- pkg/result/results.go
- pkg/simulation/run.go
- pkg/simulator/simulator.go
If the new CLI option `--debugMinMax` is given, will additionally output min/max-DPS runs' debug logs in `debug_min_dps_run` and `debug_max_dps_run` JSON fields in the output.
Tested with doing a sim and tallying up the damage from the 3 debug runs:
```
$ tools/gcsim_tools.py show-damages /tmp/gcsim.out.gz.gz | pc -1 | get_sum
698147
$ tools/gcsim_tools.py show-damages /tmp/gcsim.out.gz.gz --debug-log-flavor debug_min_dps_run | pc -1 | get_sum
423780
$ tools/gcsim_tools.py show-damages /tmp/gcsim.out.gz.gz --debug-log-flavor debug_max_dps_run | pc -1 | get_sum
809334
```
> Support outputting debug log for min/max-DPS runs

- internal/artifacts/exile/exile.go
- internal/artifacts/heartofdepth/heartofdepth.go
- internal/artifacts/huskofopulentdreams/huskofopulentdreams.go
- internal/artifacts/instructor/instructor.go
- internal/artifacts/maiden/maiden.go
- internal/artifacts/noblesse/noblesse.go
- internal/artifacts/paleflame/paleflame.go
- internal/artifacts/reminiscence/reminiscence.go
- internal/artifacts/scholar/scholar.go
- internal/artifacts/tenacity/tenacity.go
- internal/artifacts/thunderingfury/thunderingfury.go
- internal/artifacts/vermillion/vermillion.go
- pkg/core/player/character/hitlag.go
also fixes:
- a bug related to char queue (loop over all actions now because insertion order isn't guaranteed, also check if a task added another task while looping over queue) 
- a bug related to hitlag extension (missing a certain check)
missing:
- 4 tom shield bonus mod hitlag is missing
rewrites:
- maiden
- noblesse (maybe closes #167)
todo:
- ~~check noblesse~~
> fix artifacts & some bugs

- pkg/conditional/conditional.go
character custom conditionals not working because the name was prefixed by `.` which needs to be removed first
> fix character custom config

- pkg/conditional/conditional.go
- pkg/conditional/keys.go
- pkg/conditional/weapon.go
| field1     | field2                | field3 | field4 | description
| ---        | ---                   | ---    | ---    | ---
| `weapon`   | `any char name`       | none   | none   | get equipped weapon key by char
| `keys`     | `weapon`/`set`/`char` | `name` | none   | get key by name
example: https://next.gcsim.app/v3/viewer/share/a77cf881-0e63-47c3-91b9-27a8a84e6ff0
> new conditions

- internal/characters/yanfei/asc.go
- internal/characters/yanfei/attack.go
- internal/characters/yanfei/burst.go
- internal/characters/yanfei/charge.go
- internal/characters/yanfei/skill.go
- internal/characters/yanfei/yanfei.go
video: https://youtu.be/O43Ws1bgyXY
sheet: https://docs.google.com/spreadsheets/d/1NslqbafUoW4rhl1D2oVeSsn0SXfvAwnxAlIlwvKY_5Q/edit?usp=sharing
also:
- adjust q burst buff name
- fix yanfei a4 hitlag in multitarget
> Yanfei frames update

- internal/artifacts/noblesse/noblesse.go
- previously noblesse only applied to wearer because of closure stuff
> fix broken noblesse implementation

- internal/characters/hutao/skill.go
second tick used a different queue method than first tick, so when the second tick happens wasn't affected by hitlag
> fix hutao bb second tick hitlag

- internal/characters/jean/burst.go
- internal/characters/jean/cons.go
- internal/characters/jean/jean.go
- internal/characters/jean/skill.go
- internal/characters/venti/aimed.go
- internal/characters/venti/cons.go
- internal/characters/venti/venti.go
The ReceiveParticle method can't be overriden unless it is moved under `internal/template/character`, so the custom ReceiveParticle methods in Jean's/Venti's code were never called. The solution is to listen to the OnParticleReceived event instead.
also:
- moves all Jean/Venti constellations to cons.go
> fix ReceiveParticle on Jean C2 / Venti C4

- internal/characters/jean/burst.go
- internal/characters/jean/cons.go
Jean C4 should not apply for the entire Q duration. It should instead apply at the same rate as the healing ticks/self swirls with a duration of 1.2s per tick.
> fix jean c4

- internal/characters/qiqi/skill.go
Qiqi E is a deployable, so its duration shouldn't be affected by hitlag.
> fix qiqi e status hitlag

- internal/characters/beidou/burst.go
The Beidou Q proc ICD is most likely tied to the deployable, so it shouldn't even be hitlag extendable by Beidou.
> fix beidou q icd hitlag

- internal/characters/albedo/skill.go
The Albedo E proc ICD is most likely tied to the construct, so it shouldn't even be hitlag extendable by Albedo.
> fix albedo e icd hitlag

- internal/characters/albedo/albedo.go
- internal/characters/albedo/cons.go
- internal/characters/albedo/skill.go
Albedo C4 and C6 should work on ticks and not with expiry -1. However, this change spams the status log in debug with albedo-c4 / albedo-c6 getting refreshed every 0.3s.
> fix albedo c4 and c6

- internal/characters/tartaglia/charge.go
- CanQueueAfter was set to the second hitmark, when it should be the earliest cancel (first hitmark)
> fix tartaglia ca

- pkg/simulator/simulator.go
This prevents the following config from returning a call stack failure:
```
options debug=true iteration=1000 duration=104 workers=30 swap_delay=12;
diona char lvl=90/90 cons=6 talent=9,9,9;
diona add weapon="favbow" refine=3 lvl=90/90;
diona add set="noblesseoblige" count=4;
diona add stats hp=4780 atk=311 er=0.518 cryo%=0.466 cr=0.311; #main
diona add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.3968 er=0.3306 em=39.64 cr=0.3972 cd=0.1324;
ayato char lvl=90/90 cons=0 talent=9,9,9; 
ayato add weapon="favsword" refine=3 lvl=90/90;
ayato add set="blizzardstrayer" count=5;
ayato add stats hp=4780 atk=311 atk%=0.466 hydro%=0.466 cd=0.622; #main
ayato add stats def%=0.124 def=39.36 hp=507.88 hp%=0.0992 atk=33.08 atk%=0.1984 er=0.551 em=39.64 cr=0.3972 cd=0.1324;
venti char …
```
> Fix double close channel error

- internal/characters/heizou/burst.go
- pkg/reactable/reactable.go
fixes #638 
Currently nearly all absorption checks (except Heizou Q) don't check for Frozen aura, but they should. This is because you can potentially apply a Frozen aura without underlying Cryo or Hydro, see #638. To fix this, I adjusted the AuraContains method to also check for frozen durability when checking for cryo (srl gave me the code).
also:
- fixes heizou q absorbing frozen instead of cryo on windmuster iris
> fix absorption checks not picking up cryo on pure frozen aura

- internal/characters/ayato/cons.go
- internal/characters/chongyun/cons.go
- internal/characters/diluc/cons.go
- internal/characters/eula/cons.go
- internal/characters/razor/cons.go
- internal/characters/yanfei/cons.go
only looking at char code here because artifacts/weapons are considered in #764/#762
without this check you'd get a float division of 0 by 0 which is NaN (doesn't crash the sim, but this shouldn't be a thing)
> add missing damagemode check where target hp is accessed

- pkg/gcs/ast/parseEnergy.go
- pkg/gcs/ast/parse_test.go
- pkg/gcs/ast/parser.go
- pkg/simulation/config.go
- pkg/simulation/example/main.go
- pkg/simulation/run.go
- pkg/simulation/setup.go
tagging #699
- `energy every=10 amount=1;` is no longer valid
- `energy once interval=300 amount=1;` and `energy every interval=480,720 amount=1;` are valid (like pre-rewrite)
> replace current energy syntax with old syntax

- internal/characters/shenhe/cons.go
- internal/characters/shenhe/skill.go
closes #788 
- mods should not delete other mods in the Amount function because it breaks the for loop over all mods (delete the c4 buff status on damage instead)
- c4 stacks should be gained after damage and not directly on quill consumption
- add logging for c4 stack gain
> fix shenhe c4

- internal/weapons/common/royal.go
Royal weapons have 0.3s ICD and do not stack multiple times in AoE.
> add icd to royal weapons

- internal/artifacts/huskofopulentdreams/huskofopulentdreams.go
4pc husk would not start its passive stack function until after a
character swapped in. We fix this by correcting the call used in Init().
https://gcsim.app/v3/viewer/share/6a597796-2d08-4138-bb6f-a24eb8a0e43b
> fix husk artifact initial stacking

- pkg/core/combat/combat.go
- pkg/gcs/expr.go
- pkg/gcs/sysfunc.go
example: https://gcsim.app/v3/viewer/share/824dc52a-3531-4fe7-b5cf-7a074b918a5e
- available only in damage mode;
- if you are using the function for dynamic duration, set more hp for the target;
> add kill_target

- pkg/core/player/exec.go
The StamPercentMod() function sums the total modifiers, but does not
output a multiplication-friendly value. We need to add it to `1` to
modify a stamina requirement.
https://gcsim.app/v3/viewer/share/d258ec21-aedd-4dd5-8238-c1d0124ed0f1
> fix charge attacks not consuming stamina

- pkg/optimization/details.go
Yelan scales off HP%, which deviates from the default optimizer
heuristic.
> add HPP to yelan optimizer substats

- internal/characters/fischl/asc.go
- internal/characters/fischl/burst.go
- internal/characters/fischl/fischl.go
- internal/characters/fischl/skill.go
- pkg/core/task/task.go
fixes #608 
- replaces the fischloz status with a bool
- changes the semantics of .fischl.oz: instead of specifiying the amount of frames it's still active for, now it instead just specifies whether oz is "active" or not (similar to .albedo.elevator) 
- fixes Oz spawn on Q: Oz should spawn at the end of animation, but he always spawned at the earliest cancel before.
core:
- fixes 0 delay tasks not being executed right away in normal task queue
live:
https://gcsim.app/v3/viewer/share/a6808c9b-140f-44d1-821f-d7ca3f10898a
after fix:
https://gcsim.app/v3/viewer/share/d9f39e3b-8d0d-4206-82db-29d82b29e8ba
config:
```
options swap_delay=12 debug=true iteration=100 duration=100 workers=30;
fischl char lvl=90/90 cons=0 talent=9,9,9;
fischl add weapon="seasonedhuntersbow" refine=5 lvl=90/90;
target …
```
> fix fischl oz conditional breaking & oz spawn from q

- internal/characters/hutao/cons.go
- internal/characters/hutao/skill.go
- internal/characters/kuki/cons.go
- internal/characters/kuki/skill.go
- internal/characters/noelle/asc.go
- internal/characters/noelle/attack.go
- internal/characters/noelle/burst.go
- internal/characters/noelle/noelle.go
- internal/characters/noelle/shield.go
- internal/characters/noelle/skill.go
- pkg/core/player/heal.go
- pkg/simulation/setup.go
Hu Tao:
- hutao c6 should check every 2s regardless of hurt and c6 icd but should only proc when at < 2 hp for this check only
- removed unnecessary c6Check call on hutao e (hutao e hp drain calls Drain(), which emits OnCharacterHurt to trigger c6Check anyways)
Kuki:
- adjusted kuki e to use Drain() in order to be able to proc HPDown related effects (like her C6)
- fix incorrect kuki e cd (was 90f = 1.5s instead 15s, my fault)
Noelle:
- fix noelle e cast not having a chance to heal
- fix noelle e hitmark being after E -> E/Q cancel
- fix noelle q cast hit 1 and 2 not having a chance to heal
- fix noelle c4 not proccing if e is recast while shield is still up 
core:
- heal logs used c.Base.HP instead of c.HPCurrent, so the logs were showing wrong previous / current hp values
- fixes …
> bugfixes - hutao c6, kuki e & c6, noelle, heal logs, superconduct

- pkg/simulation/run.go
Need to think about this still because with this change, any damage mode sim will end immediately after the last action's animation ends. This means that any queued tasks (including the one from last action) will not execute
> end sim in damage mode when no more action

- internal/characters/ayaka/skill.go
- internal/characters/kaeya/skill.go
- internal/characters/lisa/skill.go
- internal/characters/thoma/skill.go
- internal/characters/venti/skill.go
- internal/characters/yaemiko/kitsune.go
- internal/characters/yoimiya/attack.go
- internal/characters/yunjin/skill.go
- adjust ayaka and kaeya comments
- lisa tap e should not be generating any particles
- thoma e should be generating 3.5 particles on average and not 3.4
- venti hold e should be generating 4 particles instead of 3
- yaemiko e particle icd should be 2.5s instead of ~2.9s
- yoimiya particles in e state should be 1 particle on 2s icd instead of 2.5 particles on 5s icd (looks like hutao copy paste)
- yunjin hold e lv. 1 should be generating 2.5 particles instead of 2.4
> fix wrong particle mechanics

- internal/characters/xiao/skill.go
also xiao a4 should only apply its buff 0.25s after cast
> fix xiao a4 applying to all types of attacks

- internal/characters/ayato/asc.go
- internal/characters/ayato/ayato.go
- internal/characters/ayato/skill.go
fixes #854 
a1: 
- illusion explosion should set namisen stacks to max because of a1 instead of just doing +1
a4: 
- fix missing check on swap that checks whether previous char was ayato, having no check messes with a4
- remove a4task in favor of just queing up a4 itself
- remove a4Icd because the icd is just the task delay, also this delay should not be affected by hitlag
e:
- the buff should start on ability start and not later (max possible slashes should be 16 and not 17)
> fix ayato a1 and a4

- internal/characters/kazuha/burst.go
- internal/characters/kazuha/cons.go
- internal/characters/kazuha/kazuha.go
- internal/characters/kazuha/skill.go
This PR is for improving the implementation of Kazuha's C2 and C6. Even though there are still some uncertainties, I believe this PR will make things more accurate when compared to before. However, this change spams the status log in debug with kazuha-c2 getting refreshed every 0.5s.
Kazuha C6 dmg up part didn't check for normal/charged/plunge and used a custom snapshot function, when it should be dynamic (fixes #605).
for sure:
- C2 ticks every 0.5s to apply the C2 buff to active char and Kazuha for 1s
unsure:
- Q field starts and ends when? assumption: starts on Initial Hit hitlag end and lasts until the last tick (needed for C2)
- C6 starts when? assumption: on E hitmark / Q Initial Hit hitlag end
TODO:
> partially fix kazuha c2 and c6

- internal/characters/tartaglia/riptide.go
- internal/characters/tartaglia/tartaglia.go
fixes #866 
before: https://gcsim.app/v3/viewer/share/03bd08c5-983f-4adf-b05f-85a17eef2bb0
after: https://gcsim.app/v3/viewer/share/ccdeec6b-7b69-46fb-80ed-bf2d8a71d9be
also changes his c4 timer to be 3.9s instead of 4s to match ingame better: https://github.com/genshinsim/gcsim/issues/866#issuecomment-1229108002
TODO:
> add missing src check to tartaglia c4 & c4 timer

- internal/characters/kaeya/burst.go
- internal/characters/kaeya/cons.go
- internal/characters/kaeya/kaeya.go
fixes #766 
tested here (turn on status and character logs): https://gcsim.app/v3/viewer/share/dd07faf3-ea73-4c56-b13b-fb0539917776
- implements kaeya c2
- adds a status for kaeya's burst ("kaeya-q")
- rewrite kaeya q tick logic to depend on burst status duration instead of the burst duration being hardcoded 8s
- adds a few comments for Kaeya's constellations
TODO:
> implement kaeya c2, rewrite kaeya q ticks

- pkg/core/player/character/mods.go
might be useful in case we: 
- decide to gut c.Core.Status
- want to give the user the option for conditionals off of char status duration
this returns 0 for char mods/status with expiry -1 (it doesn't really make sense to do conditionals off of that anyways? also Duration() in c.Core.Status doesn't check for that)
c.Core.Status has a Duration() function, char status/mod doesn't
> get duration for char mod

- app/src/Components/Select/OmniSelect.tsx
- cmd/wasm/main.go
- pkg/simulator/simulator.go
This fixes an issue where people running TTK sims on web/wasm would have their sim stats set to the default duration value (0 for most cases).
EDIT: this fixes #840.
> fix wasm sim not computing sim duration correctly

- internal/characters/itto/charge.go
- internal/characters/itto/itto.go
- internal/characters/itto/skill.go
previous C6 fix didn't recalculate the C6 proc when checking for CA1/CA2 -> CAF, which is wrong.
also replaces old hitbox methods with the newer calls.
tested here: https://gcsim.app/v3/viewer/share/7e139306-0bd8-4055-a461-e1d55f4e0047
> fix itto c6 and replace old hitbox methods

- internal/characters/mona/asc.go
- internal/characters/mona/cons.go
- internal/characters/mona/dash.go
- internal/characters/mona/mona.go
closes #873 
closes #874 
C1 Vaporize bonus is not getting snapshot at the current moment even though it should, so ReactBonusMod needs to be refactored in order to fix this. See https://library.keqingmains.com/evidence/characters/hydro/mona#mona-c1-snapshot-for-vape.
- also adjust a1 logs
> implement mona c1 and c6

- internal/characters/ningguang/ningguang.go
This was checking as a string and not an int.
> fix ningguang prevAttack conditional not int

- pkg/core/task/task.go
- pkg/core/task/task_test.go
This sets the ground to allow for damage to be potentially queued to the end of the current frame (allowing srp and dendro reactions to work properly)
> allow tasks to be queued to end during run

- internal/weapons/sword/darkironsword/darkironsword.go
With Version 3.0 the description of Dark Iron Sword was changed to:
```
Upon causing an Overloaded, Superconduct, Electro-Charged, Quicken, Aggravate, Hyperbloom, or Electro-infused Swirl reaction, ATK is increased by 20/25/30/35/40% for 12s.
```
This PR includes Quicken/Aggravate/Hyperbloom as trigger conditions (Hyperbloom is commented out for now) and rewrites the trigger condition to listen to OnReaction instead of OnDamage.
> rewrite darkironsword, update trigger condition for dendro

- internal/characters/heizou/heizou.go
- internal/characters/kazuha/asc.go
- internal/characters/kazuha/burst.go
- internal/characters/kazuha/kazuha.go
- internal/characters/kazuha/plunge.go
- internal/characters/kazuha/skill.go
- internal/characters/sayu/sayu.go
- internal/characters/sayu/skill.go
- internal/characters/sucrose/burst.go
- internal/characters/sucrose/cons.go
- internal/characters/sucrose/sucrose.go
- internal/characters/traveleranemo/burst.go
- internal/characters/traveleranemo/skill.go
- internal/characters/traveleranemo/traveleranemo.go
- internal/characters/venti/asc.go
- internal/characters/venti/burst.go
- internal/characters/venti/venti.go
This PR fixes cases in which the absorption location was not reset on every ability use (Kazuha E, Traveler (Anemo) E and Q) and adjusts the variable naming/logging to use "absorb" instead of "infuse" (+ a few formatting adjustments).
> fix anemo absorption location and naming

- internal/characters/kokomi/burst.go
- internal/characters/kokomi/cons.go
- internal/characters/kokomi/skill.go
- c2 above the healing of skill/burst cuz after the healing from the talent may not work the condition `active.HPCurrent/active.MaxHP() <= .5` (e.g. char has 49% hp, https://gcsim.app/v3/viewer/share/b16d440d-013e-43f7-8702-dd0fb9f85b48)
- max hp & heal bonus (c2) have a snapshot (https://www.youtube.com/watch?v=oDKhwAV7bX8)
> fix c2 kokomi

- pkg/gcs/ast/parse.go
allows for the following syntax which is a bit to easier to use to write apl
```
switch {
case <some condition>:
case <some other condition>:
default:
wait(1);
}
```
> allow condition to be optional in switch statement

- pkg/gcs/stmt.go
switch eval wasn't checking if default case is nil, causing it to crash
> fix eval switch no default case

- pkg/reactable/bloom.go
Based off these videos, the dendro core is counted as a gadget starting at ~20f from the bloom reaction trigger. This is also the time when the 5 dendro core limit is checked. The delay on damage is likely caused by the 12f linger of the core after being ruptured, hyperbloomed, or burgeoned.
The spawn delay is probably not always 20f. My hypothesis is that it is variable depending on the spawn location of the gadget. However for the sim, 20f suffices.
https://discord.com/channels/845087716541595668/869210750596554772/1027611051124064356
> change bloom dendro core delay to 20f

- app/src/Components/Nav/Nav.tsx
When clicking a share link or opening the site from not the root, logo is unable to load. Fixing the path so it can load regardless of entry point.
Before:
After:
> Fixed UI logo path so it can load from any page

- pkg/agg/result.go
- pkg/agg/util/util.go
Fixing bug for SD to return `0` instead of `NaN` when running a single iteration simulation
> Fix bug with SD when running a single iteration

- services/pkg/store/store.go
As the result schema evolves, schemas may no longer be perfectly compatible with the golang model. To increase code durability, reducing the unmarshal scope for the `DecodeViewer` in services to only the necessary data (just the config file) to keep unmarshal functional regardless of what schemas get changed.
> Reduced DecodeViewer scope to only config

- internal/characters/cyno/burst.go
If Cyno left burst early, his 14s and 18s skill CD tasks would still fire. We fix this by setting the src value to invalidate these tasks.
> fix crash when cyno swaps out of burst early

- internal/characters/fischl/asc.go
- internal/characters/fischl/burst.go
- internal/characters/fischl/skill.go
fischl a4 now has radius of 0.5m
fischl a4 now hits gadgets
fischl a4 now procs on hyperbloom trigger
fischl q now has radius of 0.5m
fischl c4 now has radius of 5m
fischl e summon now has radius of 2m by default, 3m if c2
fischl e summon now centers on primary target
> fischl radius update

- internal/characters/cyno/cons.go
Cyno's c6 can only trigger every 0.4s.
> fix cyno c6 not implemented with ICD

- internal/characters/candace/cons.go
Turns out this is affected by poise broken.
> add def halt to candace c6

- pkg/conditional/conditional.go
This is useful for telling the user the current state (or last executed action) of the player for apl sims.
Example: https://gcsim.app/v3/viewer/share/e062818f-8d18-499b-b287-690b2c22bcd4
It might be a bit cryptic to read `.state == 1`, which means current state is attack. Although the best solution is to use strings, one solution would be to have some constants/enums to represent the possible states, such as `.state == .enum.dash`.
> add .state conditional

- internal/characters/xiao/plunge.go
It's annoying to evaluate a conditional while Xiao is during plunge animation. It should be at the tail end to allow better eval.
> fix xiao plunge CanQueueAfter breaking conditionals

- internal/weapons/bow/predator/predator.go
- internal/weapons/sword/swordofdescension/swordofdescension.go
> add passive param to platform dependent weapons

- internal/characters/fischl/cons.go
- internal/characters/fischl/fischl.go
- internal/characters/fischl/skill.go
fixes #940 by adding a default travel of 10f to fischl's c6
TODO:
> add travel to fischl's oz (e and c6 procs)

- pkg/conditional/character.go
Sometimes it's useful to know how long a status lasts before it expires. This also isn't a breaking change for most configs, so it should be safe enough to apply.
> change .mods and .status to return StatusDuration()

- internal/characters/xiao/cons.go
- internal/characters/xiao/plunge.go
- internal/characters/xiao/xiao.go
fixes #1064 
- xiao c6 required 3 hits to proc before
- xiao c6 didn't allow for 3 consecutive skills without charges being consumed before
> fix xiao c6

- internal/characters/kuki/cons.go
- internal/characters/kuki/kuki.go
- internal/characters/kuki/skill.go
closes #1138 
only affects teams where Kuki gets CD reduction (4 tf, sac sword, c2 chongyun, anemo resonance, ...) and you cast her E again before it's supposed to be over originally 
fix tested here: https://gcsim.app/v3/viewer/share/998b8750-1e60-44b9-be73-fa697a637c89
> fix kuki e stacking infinitely due to missing src check

- pkg/target/icd.go
If the ICD counter exceeds the length of the array, the last value should be used.
> fix ICD not using last sequence value for default

- pkg/target/target.go
Will set target direction to the `DefaultDirection` when there are no enemies left in the simulation (no living enemies).
> Fixed direction set to work when no enemies

- internal/characters/nahida/skill.go
Needs to be doing a status check and not a duration check for cd reduction to occur.
> Fixed TriKarmaInterval to use status check

- internal/characters/alhaitham/plunge.go
It is very unrealistic to consistently do the short variant of low plunge. After this PR it will default to the shortest long version frames and you can go back to the old behaviour via a param called `short` (has to be >0).
> adjust alhaitham low plunge default length

- internal/characters/shenhe/burst.go
- 38f -> 36f, because it should apply for 0.6s
> fix shenhe a1, c2 and q shred duration

- internal/characters/yelan/aimed.go
- internal/characters/yelan/skill.go
- internal/characters/yelan/yelan.go
- tag -> bool
- add char condition: .yelan.breakthrough
- "barb" -> "breakthrough" to avoid overlap with barbara alias
> refactor yelan breakthrough state

- internal/characters/zhongli/stele.go
- internal/characters/zhongli/zhongli.go
- pkg/core/construct/handler.go
- fix construct not getting re-added on refresh
- fix zhongli stele
- stele tick shouldn't also do resonance routine on the other stele
- initial dmg should be able to generate energy
- energy gen refactored into callback
- energy gen check should not happen per stele/resonance attack
- energy gen icd should apply to zhongli and be affected by hitlag 
https://gcsim.app/v3/viewer/share/be7ad1a6-df09-4a46-b198-4d8144dfeaae
> fix constructs and zhongli stele

- internal/characters/sara/burst.go
After further investigation, 3.6m seems to be more accurate than 6m.
> fix sara q stormcluster initial offset

- pkg/core/player/character/character.go
- pkg/core/player/character/hitlag.go
- pkg/core/player/character/mods.go
- pkg/enemy/enemy.go
- pkg/enemy/hitlag.go
- pkg/modifier/modifier.go
- pkg/queue/tasks.go
This change will increase the net number of hitlag extension frames that occur. By moving the `ceil` operation to the `ApplyHitlag` function we:
1. treat each `ApplyHitlag` delay as an independent timer that expires on the frame (not such thing as perfect timing). For mods, multiple extensions are now `ceil(extension)*N` instead of `ceil(extension*N)` (as N increases, new approach will net more extension than before)
2. ceil the extenstion added to `frozenFrames` (as described above) such that anything added via `QueueEnemyTask` or `QueueCharTask` will have the same frame extension behavior as observed with modifiers
As an example of this change, currently in gcsim not possible to do `11N2CD` with Hu Tao due to `paramita` mod expiring during the 11th combo attack. There is only 19f left …
> Updated hitlag extension to ceil on ApplyHitlag

- internal/characters/hutao/charge.go
Updating CA frames to match V2 frame data for Hu Tao: https://docs.google.com/spreadsheets/d/1KR_FMtupIbLEhWRGww2N2UKEJG3hy5mWJIez8S6EZ2w/edit#gid=2118558486
Change makes 9N1C possible on hu tao
> Reduced Hu Tao CA in E to 42 frames

- internal/characters/ayaka/dash.go
- internal/characters/mona/dash.go
- internal/characters/wanderer/dash.go
- internal/template/character/stam.go
- pkg/core/action/failure.go
- pkg/core/player/character/character.go
- pkg/core/player/exec.go
- pkg/core/player/player.go
Closes #892
Example sim with dash CD and lockout being retained between swaps
https://gcsim.app/v3/viewer/share/7ea7f12d-4a2f-4ce9-bd1e-e79e75ba7616
**Note:** in current state:
* in-game 3N2CD (using macros) hits dash lockout on 3rd dash (so 2nd happens while first is in 0.8s CD w/ hitlag extension). Video: https://www.youtube.com/watch?v=IdBaKWc3-5Q
* In sim, dash lockout does not happen (with hitlag extension, first dash cd ends on frame 127 [see extension on frame 117], second dash starts on frame 128): https://gcsim.app/v3/viewer/share/5ac1e788-f3cb-4d22-807f-c8c6f334b08a
* in-game 3N2CD (using macros) will **only** hit lockout with hitlag extension
> Implements Dash CD

- internal/characters/alhaitham/plunge.go
Actually has no effect on the sim since infusion is active when low plunge is executed.
> fix alhaitham low plunge element in code

- internal/characters/kazuha/plunge.go
- internal/characters/kazuha/skill.go
- glide cancel is now possible via the `glide_cancel` param on Kazuha's `skill` (>0 means glide cancel)
- small refactoring of skill.go
- restricts his plunge to only be allowed after a Skill without Glide Cancel
> implement kazuha glide cancel

- internal/characters/raiden/skill.go
Burning is sourced to the target, not to the character. Thus this clause needs to be added.
> fix raiden skill procing on burning

- pkg/reactable/freeze.go
- pkg/reactable/reactable.go
Freeze resistance affects the duration of freeze rather than gauge. We incorporate this by reducing ModifierFrozen durability via function of decay rate.
> fix freeze resist reducing gauge instead of decay

- internal/characters/nahida/skill.go
Make Nahida's Hold Duration be the amount from frames its held longer than the minimum rather than the exact number of frame until hitmark. This is more intuitive to use
> Make Nahida hold duration more intuitive

- internal/characters/itto/dash.go
- internal/characters/itto/skill.go
closes #1267 
Itto's NA counter now correctly resets if chaining dashes or doing D -> E. Reset via timer (N1 -> E -> wait a long time -> N1) is not implemented.
E -> E frames should be the same as E -> CA/D/J as can be seen here: https://youtu.be/oa0njfapZeE?t=22
> fix itto na counter not being reset correctly and itto e -> e frames

- internal/characters/xiangling/burst.go
closes #1279 
- before: 2nd initial, 3rd initial, 1st pyronado, c6
- now: 2nd initial, 1st pyronado, c6, 3rd initial
tested here: https://gcsim.app/v3/viewer/share/527670f3-a676-4004-89c0-4cac668ce6bd
> fix xiangling c6 not applying to 3rd initial

- pkg/core/player/character/hitlag.go
- pkg/core/player/character/mods.go
- pkg/core/status/status.go
- pkg/enemy/hitlag.go
- pkg/modifier/modifier.go
closes #1291 
This means the status log category will be even more crowded, example: https://gcsim.app/v3/viewer/share/d932879c-8d28-4470-bf99-fa8806b8d39d
> add mod extension logs and adjust status extension log

- internal/tests/characters/characters_test.go
- internal/tests/collision/collision_test.go
- internal/tests/reactable/reactable_test.go
- pkg/core/core.go
- pkg/core/player/character/character.go
- pkg/core/player/character/profile/profile.go
- pkg/gcs/ast/item.go
- pkg/gcs/ast/keys.go
- pkg/gcs/ast/parseCharacter.go
- pkg/reactable/reactable_test.go
closes #857 
- before: hutao char lvl=90/90 cons=0 talent=9,9,9 start_hp=1;
- now: hutao char lvl=90/90 cons=0 talent=9,9,9 +params=[start_hp=1];
This is a breaking change for configs that utilize start_hp (mostly hu tao sims), but with this change start_hp and start_energy syntax will be consistent.
> move start_hp to params in char line

- internal/artifacts/gambler/gambler.go
- internal/characters/cyno/cons.go
- internal/characters/cyno/skill.go
- internal/characters/kirara/skill.go
- internal/characters/mika/skill.go
- internal/characters/razor/skill.go
- internal/characters/sayu/cons.go
- internal/characters/sayu/skill.go
- internal/characters/shenhe/skill.go
- internal/characters/traveleranemo/asc.go
- internal/characters/traveleranemo/skill.go
- internal/characters/yoimiya/burst.go
- internal/weapons/common/sacrificial.go
- pkg/core/attacks/icd.go
closes #216 
some bigger changes:
- fix sayu c2 (before it was gone after 1 DoT hit, now it buffs both normal and absorbed kick only)
- fix sacrificial series checking for hold e attack tag (should only check for normal e attack tag)
> hold e related fixes

- internal/characters/xiangling/asc.go
- internal/characters/xiangling/skill.go
closes #1132 
- `skill[a4_delay=1]` for picking up on active char 1f (1 <= delay <= 600) after guoba expiry (concept taken from sapwood blade)
- adjust `xianglingguoba` status: 
- make it start at t=13f instead of t=0s (relative to skill cast) since that's when guoba actually spawns
- move it to xiangling's column in the debug log by making it a char status
- make the duration line up with actual guoba duration (500 -> 438)
> add xiangling a4 via param and adjust xianglingguoba status

- internal/artifacts/crimson/crimson.go
- internal/artifacts/flowerofparadiselost/flowerofparadiselost.go
- internal/characters/mika/asc.go
- internal/characters/mika/cons.go
- internal/characters/mika/mika.go
- internal/characters/mika/skill.go
- internal/characters/razor/burst.go
- internal/characters/razor/razor.go
- internal/characters/razor/skill.go
- internal/weapons/catalyst/mappa/mappa.go
- internal/weapons/claymore/beacon/beacon.go
working on #203 
- done
- crimson witch 4pc -> 2pc increase (also adjust mod name: cw-4pc -> crimson-4pc-stacks)
- flower of paradise lost 4pc increase
- mika a1
- razor q speed burst (also adjust mod name: speed-burst -> razor-q)
- razor e energy sigil (also adjust mod name: er-sigil/razor-sigil-duration -> razor-sigil)
- mappa mare (also adjust mod name: mappa/mappa-mare-stacks -> mappa-mare)
- beacon
- TODO (part of separate PR after mods and stats array rewrite since these require new enemy mods, namely ones to influence dmg bonus/crit rate buffs tied to an enemy):
- ganyu c4 damage bonus
- mona burst damage bonus
- mona c4 crit rate
- toukabou shigure damage bonus
- considered changing these but I don't think it's feasible (**person reviewing the PR should double-check**):
- husk 4pc …
> change some mods from expiry -1

- internal/characters/cyno/burst.go
- internal/characters/cyno/cyno.go
- internal/characters/cyno/skill.go
closes #1117 (4tf proc during q now has an effect on the e cd post q expiry)
open to a less hacky solution that allows for proper cooldown reduction tracking
- abuse low plunge action for e (in q) cooldown tracking
- sims checking for e (in q) cooldown need to change from `.cyno.skill.ready` to `.cyno.low_plunge.ready`
> fix cyno cd mechanics

- internal/characters/ayaka/charge.go
- pkg/core/attacks/icd.go
- pkg/core/combat/gadget.go
- pkg/core/combat/select.go
- fix ayaka ca icd
- add distinction between enemy (only dendro core and dmc q for now) and allied gadget (needed for ayaka ca)
- fix ayaka ca logic
- delay first enemy check until before first ca hit
- pick an anchor enemy to use for chargeArea
- queue up ca hits to follow moving enemy
> fix ayaka ca and adjust gadget selection

- pkg/core/geometry/circle.go
- if both segments are completely inside of the target circle, it should count as an intersection
live: https://gcsim.app/v3/viewer/share/a863178a-f468-48a5-be7c-9cc588087b3a
pr: https://gcsim.app/v3/viewer/share/cc057fe9-2b87-4ba9-90ae-14f46f233c26
desmos visualization: 
Kirara's attack is the blue circle (fanAngle of 270 degrees, so the small area between the segments at the bottom is the no-hit zone of the circle) and the target is the red circle. As you can see both of the circle line segments of Kirara's attack are completely inside of the target's hitbox. In the current implementation this means there's no intersection, since the line segments do not run through the edge of the red circle. It should actually detect the intersection here and return that an intersection occured. (The …
> fix circle fan collision edge case

- internal/characters/itto/dash.go
- internal/characters/itto/skill.go
- was bugged when actions are put between skill and dash
- closes #1403 
- tested here: https://gcsim.app/v3/viewer/share/8bbd72c2-8836-4b3c-8bda-4dde5156e460 (turn on just action, damage and user in the log options for the optimal viewing experience)
> fix itto na counter not being reset correctly (again)

- internal/characters/albedo/albedo.go
- internal/characters/aloy/aloy.go
- internal/characters/ayato/ayato.go
- internal/characters/beidou/beidou.go
- internal/characters/bennett/bennett.go
- internal/characters/diluc/diluc.go
- internal/characters/fischl/fischl.go
- internal/characters/hutao/hutao.go
- internal/characters/kaeya/kaeya.go
- internal/characters/klee/klee.go
- internal/characters/nahida/nahida.go
- internal/characters/noelle/noelle.go
- internal/characters/sucrose/sucrose.go
- pkg/core/player/character/character.go
- pkg/simulation/run.go
- fix ayato c3 and c5 being swapped
- from this point onwards, skill cons being 3 and burst cons being 5 is no longer default and char implementations have to specify NormalCon/SkillCon/BurstCon if they should be enabled at a certain constellation, default value is -1 which means that it doesn't apply at any constellation
> Add possibility for normal cons

- ui/packages/docs/src/components/Frames/data.json
add video links for the [cam cancel sheet](https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing), where changes occured in https://github.com/genshinsim/gcsim/pull/906 (tighnari's were part of his initial implementation pr)
> add cam cancel related video links to docs

- ui/packages/docs/docs/reference/config.md
name for options duration and iteration were swapped + some reordering of rows in the table
> fix swapped options in config docs

- pkg/agg/fieldtime/fieldtime.go
capacity set to actual number of chars instead of hardcoding to 4
> adjust hardcoded field time aggregator capacity

- pkg/agg/damage/damage.go
- pkg/stats/damage/damage.go
- pkg/stats/result.go
closes #1563 
Splits the abilities of the source dps graph into reaction/non-reaction with no option to group them together again for now.
Example image:
> add back reaction/non-reaction source dps split

- ui/packages/ui/src/Pages/Viewer/Components/Miscellaneous/SourceReactionsBarChart/BarChart.tsx
before:
after:
crystallize-electro is the longest reaction name we have.
> fix source reaction bar chart text cutting off

- internal/characters/wanderer/burst.go
- internal/characters/wanderer/cons.go
- internal/characters/wanderer/plunge.go
also move wanderer plunge available deletion to avoid conflicts with CanQueueAfter vs. OnRemoved timing
> fix rare wanderer c6 - burst bug

- internal/characters/keqing/asc.go
- internal/characters/keqing/skill.go
- fix keqing recast e -> dash frames and CanQueueAfter
- fix keqing A1 duration so that it entirely covers 5 N1C since that is possible ingame, see #567. In the live version, the CA-2 hit of the final CA was not covered by the A1 infusion.
closes #1400
> keqing recast e -> dash and CanQueueAfter, keqing a1 duration

- internal/characters/xingqiu/burst.go
- internal/characters/xingqiu/skill.go
- ui/packages/docs/src/components/Params/character_data.json
since the hitbox refactor the same effect can be achieved by moving the player/target, see <https://docs.gcsim.app/reference/system_functions#set_player_pos> so that the orbital aoe (1.3m radius around player) does not hit.
need opinions on this because this breaks all sims using orbital=0 that do not adjust player/target pos
> remove xingqiu e/q orbital param

- internal/characters/wanderer/asc.go
- internal/characters/wanderer/skill.go
- internal/characters/wanderer/wanderer.go
- fix a1 checking on interval instead of only once on cast (meaning a1 could be absorbing the 2nd or 3rd (C4) element after skill cast)
- fix a1 not being able to absorb >1 or >2 (C4) elements on cast
> fix wanderer a1

- internal/characters/keqing/asc.go
- internal/characters/keqing/attack.go
- internal/characters/keqing/charge.go
https://discord.com/channels/845087716541595668/1138052124803076167
[Sample](https://github.com/genshinsim/gcsim/files/12294141/keqingceiling.gz) to upload [here](https://gcsim.app/sample/upload).
Config:
```
options swap_delay=12 iteration=1;
energy every interval=480,720 amount=200;
keqing char lvl=90/90 cons=0 talent=10,10,10;
keqing add weapon="dullblade" refine=1 lvl=1/20;
keqing add set="tf" count=4;
keqing add stats atk=42 cr=0.311 ; #main
keqing add stats atk=14 atk%=0.095  em=39.627 cd=0.287;
nahida char lvl=90/90 cons=4 talent=8,10,10;
nahida add weapon="apprenticesnotes" refine=1 lvl=1/20;
collei char lvl=90/90 cons=6 talent=9,9,9;
collei add weapon="huntersbow" refine=1 lvl=1/20;
active nahida;
target lvl=85 resist=0.1 radius=2 pos=0,2.4 hp=999999999; 
nahida skill;
wait(60); …
```
> fix keqing a1, na/ca frames and n1 -> ca

- internal/characters/wanderer/asc.go
- internal/characters/wanderer/skill.go
https://discord.com/channels/845087716541595668/1140029212607139880
Also adjust the char logs for wanderer a4 ("proc'd" moved to when a4 actually fires off arrows and added "available" log for when a4 is available to be used).
> fix wanderer a4 being able to proc 2 times in 1 dash

- internal/artifacts/marechausseehunter/marechausseehunter.go
cli shows the reason `simulation panic occured: interface conversion: interface {} is float64, not int` while UI loads infinitely.
> fix mh sims running infinitely on heal

- internal/artifacts/goldentroupe/goldentroupe.go
the program chashed due to no initialization of `buff` when no 4pc gt
> fix goldentroupe 2pc

- internal/weapons/catalyst/flowingpurity/flowingpurity.go
- internal/weapons/sword/finaleofthedeep/finaleofthedeep.go
From [Discord](https://discord.com/channels/845087716541595668/1143010182562062377/1143010182562062377):
Sample before commits: https://gcsim.app/sh/FWJWTC7CgTfk#sample=10236862637200687826&tab=sample
HP bonds were previously: 
1) activating on any ally skill (47f)
2) giving a flat atk buff lower than intended by a factor of 1000 (531f, atk gain should be 233 not 0.23)
> fix hp bond weapons atk calc and active unit check

- internal/artifacts/marechausseehunter/marechausseehunter.go
don't want to bloat on heal event sub with prev hp, so doing some floating point comparison
> fix mh triggering on heal if hp already max

- pkg/gcs/eval.go
- pkg/gcs/expr.go
- pkg/gcs/stmt.go
Fixes following error on existing sims:
```
fn random_wait returned an invalid type; got 0
```
> force functions to return number if null return

- internal/characters/fischl/skill.go
- if oz despawns after q start then ozActive stayed 0
[Sample](https://github.com/genshinsim/gcsim/files/12447673/oz.gz)
> fix fischl oz conditional breaking during q

- cmd/gcsim/main.go
- ui/packages/docs/docs/reference/cli.md
Add two options (`-sampleMinDps` and `-sampleMaxDps`) analogous to `-sample` for saving the min/max-DPS runs as a sample.
Tested with:
```
$ \cp ~/Programming/Git/gcsim/cmd/gcsim/gcsim bin/gcsim && tools/gcsim_tools.py run-sim data/rotations/yanfei-xingqiu-kazuha-bennett.txt --working-dir /tmp/gcsim-out && ll /tmp/gcsim-out/baseline
baseline        | duration  70.0s | avg      32439 (  0.0%) | span      20629 -      35548 std       1263
total 9040
-rw-r--r--  1 jiahaoli  wheel   2.1K Aug 27 15:00 config.txt
-rw-r--r--  1 jiahaoli  wheel    95K Aug 27 15:00 result.json
-rw-r--r--  1 jiahaoli  wheel   1.6M Aug 27 15:00 sample.json
-rw-r--r--  1 jiahaoli  wheel   1.6M Aug 27 15:00 sample.max_dps.json
-rw-r--r--  1 jiahaoli  wheel   1.2M Aug 27 15:00 sample.min_dps.json
-rw-r--r--  1 jiahaoli …
```
> Add CLI options for saving min/max-DPS runs as samples

- ui/packages/db/src/SharedHooks/databaseQuery.ts
Force DB results to always sort by newest to oldest. To be changed in future when we add actual UI elements for other sorting options
> force db default sort by create_date

- pkg/agg/damage/damage.go
If there is at least 1 iteration where a char's element dps is 0, then the entire char's element dps will be discarded/not shown.
Example: char 0 has phys dps of 0 in at least 1 iteration -> discard phys dps across all iterations entirely
> fix element dps being 0 if min is 0

- pkg/agg/warnings/warnings.go
- low std but "high" mean should lead to a warning
threshold condition is consistent with the other warnings now
> fix energy warning condition leading to no warning

- pkg/gcs/ast/parse.go
- pkg/simulator/simulator.go
instead of always showing "sim has errors" for certain errors, now the actual error messages will be shown
example:
> fix config page not displaying exact errors

- pkg/gcs/ast/node.go
- pkg/gcs/ast/parseFn_test.go
- pkg/gcs/ast/parseTyping.go
Add `map` typing to function declarations. To allow future typing of `execute_action` properly. This should also ensure any current usage of the following is future compatible:
```
fn rand_delay(mean, stddev) {
let del = randnorm() * stddev + mean;
if del > (mean + mean) {
del = mean + mean;
}
delay(del);
}
let prev_char_id = -1;
let prev_action_id = -1;
let _execute_action = execute_action;
fn execute_action(char_id number, action_id number, p map) {
print(prev_char_id, " ", prev_action_id, " ", char_id, " ", action_id);
if action_id == .action.swap {
rand_delay(12, 3);
} else if prev_action_id == .action.attack && action_id != .action.attack && action_id != .action.charge {
rand_delay(3, 1);
} else if prev_action_id != .action.attack {
rand_delay(3, 1);
}
prev_char_id = char_id; …
```
> add map typing

- internal/characters/xiangling/skill.go
- ui/packages/docs/src/components/Params/character_data.json
closes #1707 
- < 0 means no a4
- default: 0 -> -1
> adjust xiangling a4 to not automatically trigger

- internal/characters/kazuha/burst.go
- internal/characters/kazuha/kazuha.go
https://discord.com/channels/845087716541595668/1152275463012618250
> fix kazuha q snapshot timing

- internal/weapons/sword/keyofkhajnisut/keyofkhajnisut.go
Fixed bug where Key would stack if the equipped character was on field for any skill damage, not just their own.
> Fix Key working when the wrong character attacks

- internal/characters/fischl/asc.go
- internal/characters/nahida/skill.go
Fixes Fischl A4 timing. This should cause it to proc after TKP as seen in game. The frame count matches personal testing that I seem to have lost the footage of.
> Fix Fischl A4 Timing

- internal/characters/jean/burst.go
https://discord.com/channels/845087716541595668/884485336657444894/1178101714176454746
- first in/out should not get fanfare buff because initial heal happens beforehand
- initial hit should get fanfare buff
Fix showcased here:
[jean-fix.gz](https://github.com/genshinsim/gcsim/files/13684175/jean-fix.gz)
> fix jean q initial hit and first in/out dmg being swapped

- internal/characters/fischl/burst.go
- internal/characters/fischl/skill.go
https://discord.com/channels/845087716541595668/1156832994556923984
- heal should happen at end of animation right after oz spawn
- example: songofstillness passive proc shouldn't snap onto burst oz
Fix is showcased here:
[fischl-c4-fix.gz](https://github.com/genshinsim/gcsim/files/13684327/fischl-c4-fix.gz)
> fix fischl c4 timing

- internal/characters/neuvillette/charge.go
- internal/characters/neuvillette/neuvillette.go
- if ticks < max ticks performed by ca, then swap will be stuck for a long time (intended because it is illegal)
- cannot error out like for other forbidden actions with ticks param
- make sure of correct swap cd calculation
- fix edge case for ticks=1 where tickAnimLength calc used wrong param
- remove unused char fields
- fix min ticks value to match docs (1 instead of 0)
> fix neuvillette ca ticks param interaction with swap

- ui/packages/ui/src/Sectioning/Nav.tsx
https://discord.com/channels/845087716541595668/1136311047045775370
Talking about:
- discord login is not implemented
> remove confusing "Guest" text top right on sim page

- ui/packages/docs/docs/reference/fields.md
found out about this as part of https://discord.com/channels/845087716541595668/1029599016234786867
- element gives durability and not just 0 and 1
- indexing starts at 0 not 1
> fix target field docs

- pkg/agg/damage/damage.go
It's not intuitive that the source instances bar chart also counts dmg instances that did 0 dmg. This is especially relevant for Hyperbloom counts.
I see no value in counting the dmg instances that did 0 dmg in that bar chart for now, but it can always be added back later in some form.
> adjust source damage instances to not count 0 damage

- internal/weapons/bow/rangegauge/rangegauge.go
- internal/weapons/claymore/powersaw/powersaw.go
- internal/weapons/spear/prospectorsdrill/prospectorsdrill.go
- internal/weapons/sword/dockhand/dockhand.go
- symbol duration is not tracked per symbol
- one status for all symbols instead of 3
- add weapon log for stack gain
- simplify code
- adjust buff/status naming
- fix bug in rangegauge/prospectorsdrill where all symbols were immediately consumed on stack gain
> adjust 4.1 4* weapon series implementations

- pkg/conditional/gadgets.go
- pkg/core/combat/gadget.go
- pkg/gcs/sysfunc.go
- pkg/reactable/crystallize.go
- ui/packages/docs/docs/reference/fields.md
- ui/packages/docs/docs/reference/system_functions.md
- before: crystallize shard immediately picked up on trigger
- now: crystallize spawns shards
- shards have to be explicitly picked up via new sys func (pick_up_crystallize)
- new conditionals to track crystallize shard count for waiting until pickup is possible (.gadgets.crystallizeshard.all/pyro/hydro/electro/cryo)
- shield is created on shard pickup
recommended usage (adjust 60 to be number of frames to wait for maximum):
```
for let k=0; k<60; k=k+1 {
if .gadgets.crystallizeshard.hydro > 0 {
pick_up_crystallize("hydro");
break;
}
wait(1);
}
```
> rework crystallize

- internal/characters/charlotte/skill.go
Fixes bug where Charlotte's hold skill frames are extended by the time until the hitmark
> Fix Charlotte Hold Skill Frames

- pkg/core/player/exec.go
- logs stam/swap_cd post (after) using the given action
> fix action exec log stam/swap_cd naming to be more accurate

- internal/characters/yunjin/burst.go
- internal/characters/yunjin/cons.go
- internal/characters/yunjin/yunjin.go
- should start at hitmark and not on cast (effectively 35f longer now)
- q, c2 and c6 status should be deleted on cast
- adjust cons checks for c2, c4, c6 to be inside of the funcs
> fix yunjin q, c2 and c6 duration

- internal/characters/navia/attack.go
https://discord.com/channels/763583452762734592/1186852199054196806/1191646579145318480
- a1 infusion should be snapshot on gadget creation
> fix navia n3 snapshot timing

- internal/frames/frames.go
- ui/packages/docs/docs/mechanics/atk_spd.md
hopefully a better approximation
green = before
orange = after
x-axis is atk spd input (0 <= x <= 0.6) and y is effective atk spd
> adjust attack speed model

- cmd/gcsim/main.go
- running GC before writing profile does not provide useful data
> fix cli -memprofile option

- pkg/core/player/animation/animation.go
- pkg/modifier/modifier.go
- ui/packages/ui/src/Pages/Sample/Components/parsev2.ts
* Add highlight to animation and `mod extended` logs
* Fix mod logs to use hitlagged expiry
* Move `mod extended` logs to char column
* Remove event name from cooldown logs `cooldown: skill cooldown triggered` -> `skill cooldown triggered`
> Bugfixes for sample logs

- internal/characters/chevreuse/skill.go
- also adjust timing for the check whether heal is currently active to happen at cd start
> fix chevreuse c4 extending heal by 12s instead of refreshing to 12s

- ui/packages/ui/src/Pages/Viewer/Components/Damage/DamageTimelineCard/CumulativeData.tsx
- ui/packages/ui/src/Pages/Viewer/Components/Damage/DamageTimelineCard/DamageOverTimeData.tsx
- now will show all buckets on timeline
> fix damage timeline graphs cutting off final bucket in some cases

- pkg/enemy/attack.go
- should not let enemy hp become negative because in the current design applyDamage can be called again in the same frame even if the previous call killed the enemy
- changed applyDamage to return the actual amt of dmg applied so that overkill does not count towards dps / cumulative damage dealt to the target
> fix sim handling enemy damage on death frame incorrectly

- pkg/agg/damage/damage.go
- pkg/agg/metadata/metadata.go
- pkg/agg/util.go
- cmp.Compare in cumu dmg and Less func in metadata did not do floating point equality via a delta making it unstable
- use slices.SortStableFunc for sorting
- also fix edge case of iterations = 1 not populating q1/q3 percentile
- move common logic as generic funcs to util package
> fix cumulative damage and metadata sorting

- pkg/stats/reaction/reaction.go
- will now also show up in "Reactions Per Source" bar chart
> fix shatter not being tracked in reaction stat

- ui/packages/ui/src/Pages/Viewer/Tabs/Config.tsx
- ui/packages/ui/src/Pages/Viewer/Viewer.tsx
- Copy to Config and Send To Simulator
- previously recovery of config from rerun on error impossible
- adjust confirm button text to be more clear about where it leads
example images (not the prettiest but good enough to drastically improve UX for rerun tab on viewer page):
> add buttons to recover config on sim runtime error

- internal/characters/wriothesley/cons.go
- so that +0 dmg% doesn't get logged
- no difference in behaviour to previous fix
> adjust wriothesley c2 to explicitly check for a4

- ui/packages/ui/src/Pages/Viewer/Components/Damage/DamageTimelineCard/index.tsx
- previously was towards top left of card instead of center of remaining space at top
> adjust damage timeline legend to fill remaining space

- ui/packages/ui/src/Pages/Sample/Components/Options.tsx
- ui/packages/ui/src/Pages/Sample/Components/SampleView.tsx
- ui/packages/ui/src/Pages/Viewer/Tabs/Sample.tsx
- now has the same width as the other tabs on viewer page
- fix sample search bar being squished on mobile
- fix log options dialog not fitting on mobile screen
- adjust horizontal scrolling to only include the gray box and not the search/settings/download
> adjust Sampler UI

- ui/packages/ui/src/Pages/Viewer/Components/Miscellaneous/TargetAuraUptimeBarChart/index.tsx
- ui/packages/ui/src/Sectioning/Nav.tsx
- fix target aura uptime card height on mid size screens not matching reactions card height
- fix opened mobile nav not being hidden if transitioning to desktop nav
> more UI adjustments

- internal/artifacts/bolide/bolide.go
- internal/characters/baizhu/shield.go
- internal/characters/beidou/burst.go
- internal/characters/beidou/skill.go
- internal/characters/candace/skill.go
- internal/characters/diona/skill.go
- internal/characters/kaeya/cons.go
- internal/characters/kirara/shield.go
- internal/characters/layla/shield.go
- internal/characters/noelle/asc.go
- internal/characters/noelle/shield.go
- internal/characters/thoma/shield.go
- internal/characters/traveler/common/hydro/cons.go
- internal/characters/xinyan/asc.go
- internal/characters/xinyan/shield.go
- internal/characters/yanfei/cons.go
- internal/characters/yunjin/skill.go
- internal/characters/zhongli/shield.go
- internal/weapons/claymore/beacon/beacon.go
- internal/weapons/claymore/bell/bell.go
- internal/weapons/common/goldenmajesty.go
- pkg/avatar/avatar.go
- pkg/core/player/shield/handler.go
- pkg/core/player/shield/shield.go
- pkg/core/player/shield/template.go
- pkg/reactable/crystallize.go
- pkg/simulation/setup.go
- shielded check should be character specific and shield target specific
- shield add should consider target of the shield for overwrite
- shield OnDamage should only damage shields that apply for the given char
- fix beidou c1 and skill sharing shield type
- fix beidou skill shield lasting for 15s instead of until hitmark
- fix bolide, geo resonance, bell dmg bonus, goldenmajesty not working off-field for 1 character shields
- fix xinyan a4 applying to phys dmg dealt from off-field characters (global shield so need active check) 
dbcompare is looking ok, biggest impact is beidou skill shield dur fix
> add ShieldTarget to shield interface and other shield fixes

- pkg/simulation/setup.go
- active should only be checked right before damage happens
> fix hurt settings having incorrect column for damage log

- internal/characters/furina/burst.go
- internal/characters/furina/furina.go
closes #1994 
- assumption: salon member hp drain will drain all chars in same frame (inconsistent ingame, assumption was not changed here)
- fanfare gain seems to have a ~0.5s debounce status and ~6f delay from hp drain confirmation from server to actual fanfare gain if debounce status is not up yet
- if debounce status is up, all fanfare changes seem to be delayed until this status is gone
- example:
- t=0f: hp drain happens, debounce status not up so queued fanfare gain to happen at t=0+6=6f and queued debounce status application at t=1f
- t=1f: debounce status applied, lasts until t=36f, any hp drains that happen while status is up will have their fanfare gain delayed until t=36f
- t=6f: fanfare gain from t=1f happens
- t=10f: hp drain happens, debounce status is up so queued fanfare …
> fix furina fanfare gain mechanics

- Taskfile.yml
- ui/packages/executors/package.json
closes #1687 
- use Taskfile in web for wasm build (requires Task to be installed on the machine)
> add wasm build to Taskfile to be windows-compatible

- pkg/core/player/exec.go
Remove redundant ability ready check on `player.Exec`, to allow for callers of `player.Exec` to potentially bypass ready check where needed (mainly for Chiori swapping)
> remove player.Exec ready check (redundant)

- internal/characters/gaming/burst.go
- internal/characters/gaming/gaming.go
- internal/characters/gaming/plunge.go
- ui/packages/docs/src/components/Params/character_data.json
- fix gaming man chai link up timing being affected by hitlag
- fix gaming man chai linking up off-field
- fix gaming man chai delay for burst specifically
- 100f instead of the 92f for the plunge
- the param value now doesn't persist after specifying once but instead needs to be supplied to every burst/plunge if it should be changed
> gaming man chai bugfixes

- ui/packages/db/src/Pages/Home/Home.tsx
- ui/packages/db/src/tags.json
after some discussion I believe renaming the delay tag to "action execution delays" or something similar is more understandable to typical viewers instead of "random frame delays", and the randomization of the delays is not technically a requirement.
> edit tag blurb and rename random frame delay tag

- internal/characters/heizou/burst.go
- Windmuster Iris missing return when nothing is absorbed
> fix heizou burst behavior when nothing is absorbed

- internal/characters/traveler/common/electro/burst.go
- pkg/enemy/types.go
- pkg/gcs/expr.go
- pkg/gcs/op.go
* Resolves #2139
* Fix dummy enemy profile (defaults to clear particles. used to be electro)
* Fix travelerelectro c2 causing a panic when disabled
> Fix division, dummy enemy profile, travelerelectro c2

- pkg/core/info/character.go
- pkg/gcs/ast/parseCharacter.go
- pkg/simulation/randstats.go
- pkg/simulation/setup.go
Proof of concept for using random substats instead of specified. Meant as an alternative to substat standards
> Random substats - POC

- internal/artifacts/echoes/echoes.go
Add icd check when the Valley Rite fails to be triggered.
Fix #2165.
> fix echoes icd bug

- internal/template/character/hp.go
The current implementation emits a negative value when HPDebt=0 and amt is negative. However, in this case, the HPDebt didn't change, so the event should emit 0 HPDebt change
> Fix BOL event emitting even if HPdebt didn't change

- internal/template/character/hp.go
The max value of Bond of Life is 200% of a character's Max HP
> add max hp debt

- internal/weapons/catalyst/surfsup/surfsup.go
> once every 1.5s, lose 1 stack after a Normal Attack hits an opponent
> fix no normal attack check on surf's up stack loss

- pkg/reactable/electrocharged.go
- pkg/reactable/freeze.go
- pkg/reactable/overload.go
- pkg/reactable/superconduct.go
- Superconduct: 0.5 → 1.5
- Shatter: 1.5 → 3
- Electro-Charged: 1.2 → 2
- Overload: 2 → 2.75
These changes apply to both characters and enemies
Reference: Bloom 2 | Burgeon 3 | Hyperbloom 3
> Update reaction multipliers

- internal/characters/clorinde/skill.go
`c6skill` is being queued before `skillStateKey` status is added
> fix clorinde c6 not adding crit bonus

- internal/weapons/sword/absolution/absolution.go
fix [discord message](https://discordapp.com/channels/845087716541595668/845087716541595671/1320755905838583890)
> fixed absolution stack gain

- internal/characters/xilonen/cons.go
- internal/characters/xilonen/skill.go
https://discord.com/channels/845087716541595668/1336939788925931561
> Fix xilonen geo sampler being active if all samplers were converted

- internal/characters/yelan/burst.go
- internal/characters/yelan/yelan.go
- ui/packages/docs/src/components/Frames/character_data.json
This PR:
- adds a `travel` param to yelan Q. default travel time is 20 frames, a bit shorter than old hitmarks.
- adds yelan N0 timing to herself.
- changes c2 hitmark.
- updates docs.
The default travel time could be different than 20 frames, it's a bit arbitrary. I attached [counts](<https://docs.google.com/spreadsheets/d/1y4r8MNm_sWfFCmELlc3qWnlf_m40veFGV3IW6KOW5Is/edit?usp=sharing>) for the first hitmark in melee range against a downed ruin guard (21 frames) and a downed aeonblight drake (18 frames), so 20 seemed like a nice default.
The subsequent Exquisite Throws will hit 6 frames after each other. In game, this can still vary based on enemy hitbox, but 6f was about the average difference from my ruin guard counts.
I don't own C2 yelan, but the old hitmark for C2 was too long. …
> Yelan burst updates (N0, travel param, C2)

- internal/template/character/ready.go
- pkg/conditional/character.go
closes #2000 
config for testing
```
options iteration=100;
energy every interval=480,720 amount=1;
hutao char lvl=90/90 cons=1 talent=9,9,9;
hutao add weapon="favlance" refine=3 lvl=90/90;
furina char lvl=90/90 cons=1 talent=9,9,9;
furina add weapon="favsword" refine=3 lvl=90/90;
target lvl=100 resist=0.1 hp=100000000 pos=0,2;
active hutao;
hutao skill;
for let i = 0; i < 3; i = i + 1 {
hutao attack, charge;
print("hutao.dash.ready: ", .hutao.dash.ready);
print("hutao.dash.cd: ", .hutao.dash.cd);
hutao dash;
}
wait(800);
for let i = 0; i < 6; i = i + 1 {
hutao attack, charge;
print("stamina: ", .stam);
print("hutao.dash.ready: ", .hutao.dash.ready);
print("hutao.dash.cd: ", .hutao.dash.cd);
hutao dash;
}
wait(500);
hutao skill, attack, charge, dash,
attack, charge, dash; …
```
> fix .char.dash.cd and .char.dash.ready fields

- internal/characters/mavuika/charge.go
Added bugfix for CAs being cut short when started near NS expiry. Skipped windup frames were not added to the NS duration, causing inaccurate CA duration and failed forced CAF queuing.
> Mavuika bugfix: new CA cut short

- internal/characters/kinich/burst.go
- internal/characters/kinich/kinich.go
- internal/characters/kinich/skill.go
- internal/characters/xilonen/cons.go
- internal/characters/xilonen/skill.go
- internal/characters/xilonen/xilonen.go
- internal/template/nightsoul/nightsoul.go
- ui/packages/docs/docs/reference/fields.md
Add functions to Nightsoul module to allow setting up NS with an optional cb for when NS status ends. This CB will only be called if NS expires via the timer, not if NS is manually expired, and is intended to clean up the character state on Nightsoul expiry. As an alternative, an OnNightsoulExpiry event could be used, or an array of cb functions could be allowed.
Kinich refactored to make use of this functionality.
GCSL users can get remaining NS duration through .<character>.status.nightsoul-blessing.
For now, it's assumed that all NS timers will be hitlag extended. If that is not the case, code can be further refactored to accept a hitlag bool, to be passed through to the char.AddStatus method call.
I manually tested a few Kinich configs and got matching results, but I have not run a …
> Add timed Nightsoul Blessing

- internal/weapons/catalyst/vividnotions/vividnotions.go
Hi!
I believe the Vivid Notions implementation has a bug where the 40% Crit Dmg buff is granted on plunge rather than on skill or burst. This change should fix it
> Fix Vivid Notions skill/burst buff

- internal/characters/kinich/cons.go
- internal/characters/kinich/kinich.go
- internal/characters/kinich/skill.go
from https://discord.com/channels/845087716541595668/1380299775802609786
currently Kinich's Scalespiker Cannon snapshots on cast, but it should snap after nightsoul points are drained.
This PR:
1. Changes Scalespiker Cannon to snap at same frame nightsoul points are drained.
2. Refactors C2, otherwise moving the snap frame would lead to using the radius variable before it is set.
3. Changes cannon `travel` time to start when nightsoul is drained, otherwise `travel=0` would land before the snapshot. 
4. Changes blindspot creation task to queue when nightsoul is drained instead of 1 frame earlier. There is functionally no difference here.
3 means that configs using `travel` will land 1 frame later than before. The default travel time is unchanged …
> adjust kinich cannon snapshot frame & refactor c2

- cmd/gcsim/main.go
- pkg/optimization/substatoptimizer.go
- pkg/optimization/substats.go
- ui/packages/docs/docs/guides/substat_optimizer.md
- ui/packages/docs/docs/reference/cli.md
Causes the optimizer to write substats into its resulting config formatted with their scalar multiplied by their substat count like this:
```
mizuki add stats def%=0.062*2 def=19.68*2 hp=253.94*2 hp%=0.0496*2 atk=16.54*2 atk%=0.0496*12 er=0.0551*4 em=19.82*6 cr=0.0331*3 cd=0.0662*5;
furina add stats def%=0.062*2 def=19.68*2 hp=253.94*2 hp%=0.0496*4 atk=16.54*2 atk%=0.0496*2 er=0.0551*2 em=19.82*2 cr=0.0331*12 cd=0.0662*10;
fischl add stats def%=0.062*2 def=19.68*2 hp=253.94*2 hp%=0.0496*2 atk=16.54*2 atk%=0.0496*4 er=0.0551*2 em=19.82*2 cr=0.0331*10 cd=0.0662*12;
xilonen add stats def%=0.062*10 def=19.68*2 hp=253.94*2 hp%=0.0496*2 atk=16.54*2 atk%=0.0496*2 er=0.0551*2 em=19.82*2 cr=0.0331*10 cd=0.0662*6;
```
-options="show_substat_scalars=0" will use the previous formatting.
> add show_substat_scalars option to optimizer (default 1)

- internal/characters/sucrose/attack.go
- internal/characters/sucrose/burst.go
- internal/characters/sucrose/charge.go
- internal/characters/sucrose/skill.go
- ui/packages/docs/src/components/Actions/character_data.json
- ui/packages/docs/src/components/Frames/character_data.json
Video https://youtu.be/zCuAAX2FUTE
Counts https://docs.google.com/spreadsheets/d/1w2kx5-gLYqyuxYisKb5gnOfA-jsM1VdpCWv04aJVcIY/edit?usp=sharing
[dbcompare.txt](https://github.com/user-attachments/files/20765912/dbcompare.txt)
A handful of configs were erroneously using walk cancels in the db so they will take a damage hit, particularly this one loses ~13% dps <https://gcsim.app/db/r7kCdHHm9kpq>
> add sucrose walk cancels

- internal/characters/lisa/burst.go
**1 Enemy:** C4 always emits 1 Discharge per Arc i.e. 100% chance to emit 1 Discharge.
--> unchanged
**2 Enemies:** C4 emits either 1 or 2 Dischages per Arc. 
- The first Arc has a different probability distribution: 
- 60% chance to emit 1 Discharge
- 40% chance to emit 2 Discharges
- For all subsequent Arcs, the probabilities change to: 
- 15% chance to emit 1 Discharge
- 85% chance to emit 2 Discharges
--> cleaner rates
**3+ Enemies:** C4 emits either 1, 2, or 3 Discharges per Arc.
- The first Arc will never emit 3 Discharges, instead having probabilities: 
- 55% chance to emit 1 Discharge
- 45% chance to emit 2 Discharges
- From there, the discharge count follows a Markov chain with the following transition probabilities:
```
| Current Arc  | Next Arc: 1 Discharge | Next Arc: 2 …
```
> update lisa c4 transitions/probabilities
