- internal/artifacts/instructor/instructor.go
- internal/characters/sara/abil.go
- internal/characters/sara/sara.go
- internal/characters/xingqiu/xingqiu.go
- internal/weapons/bow/viridescent/viridescent.go
- run.go
- worker.go
Fixes:
Incorrect Instructor buff timing
Sara C6 double procs
Xingqiu orbitals having incorrect duration during burst, and proccing at the
wrong times
Final DPS output was over 1 frame less than actual
> Bugfixes - Instructor, Sara C6, XQ Orbitals, VHunt Procs, DPS Output

- internal/weapons/catalyst/mappa/mappa.go
- internal/weapons/catalyst/prayer/prayer.go
- internal/weapons/catalyst/skyward/skyward.go
- internal/weapons/catalyst/widsith/widsith.go
- internal/weapons/spear/kitain/kitain.go
- internal/weapons/sword/mistsplitter/mistsplitter.go
- pkg/core/stats.go
> fix ele dmg incorrectly adding to all dmg

- internal/artifacts/archaic/archaic.go
- internal/characters/diluc/diluc.go
- internal/characters/fischl/asc.go
- internal/weapons/spear/kitain/kitain.go
- pkg/monster/damage.go
Fixes the following bugs:
Petra A4 was not applying to all characters in party
Diluc infusion times and frames were off compared to KQM
Diluc snapshot timing fixed (#31)
Fischl A4 now procs on electro crystallize
Crystallize now triggers a "OnTransReaction" event
Kitain buffed elemental damage and not elemental skill damage
> Bugfixes: Petra 4pc, Diluc, Fischl A4, Crystallize Events, Kitain

- internal/characters/albedo/albedo.go
- internal/characters/bennett/bennett.go
- internal/characters/xiao/abil.go
- internal/characters/xiao/xiao.go
- pkg/core/construct.go
Fixes:
- Albedo E duration was incorrect and ICD did not reset after replacing E
- Added new Bennett buff per-character status
- Moved Xiao E charge into tags
- Construct refreshing didn't work if there is only one construct on field
> Bugfixes: Albedo E, Bennett buff status, Xiao charge tags, construct

- internal/artifacts/tenacity/tenacity.go
- internal/characters/albedo/albedo.go
- internal/characters/aloy/abil.go
- internal/characters/amber/amber.go
- internal/characters/diona/diona.go
- internal/characters/ganyu/abil.go
- internal/characters/kokomi/abil.go
- internal/characters/sara/abil.go
- internal/characters/tartaglia/abil.go
- internal/characters/venti/abil.go
- internal/weapons/bow/amos/amos.go
- pkg/character/tasks.go
- pkg/core/snapshot.go
Bugfixes: Tenacity, Albedo E and Q, Kokomi E particles
Fixes Amos stack calculation issue and starts fixing aimed snapshot
Amos stack fix is incomplete for all characters - need to fix the snapshot timing for all bow characters.
> Various bugfixes: Tenacity, Albedo E and Q, Kokomi E particles, Amos stacking

- internal/characters/fischl/fischl.go
> fix fischl c6 initial hit

- resonance.go
Fixed geo resonance
- Buffs only affect on-field character
- 15% dmg bonus can't be snapshotted
> Fix geo resonance

- cmd/gcsim/main.go
- sim.go
- worker.go
I can't figure out for the life of me why git completely died on worker.go and thinks the whole file changed...
> Add damage over time statistics to the json results output

- internal/characters/diona/diona.go
- pkg/core/core.go
- pkg/core/stam.go
> add stam mod key

- internal/characters/sucrose/abil.go
- internal/characters/xiangling/guoba.go
- internal/characters/xiangling/stats.go
- internal/characters/xiangling/xiangling.go
- internal/characters/xiangling/xiangling_test.go
- pkg/core/combat.go
- pkg/core/events.go
- pkg/core/target.go
- sim.go
> guoba swirl

- internal/characters/hutao/abil.go
- internal/characters/noelle/abil.go
- internal/characters/noelle/noelle.go
- internal/characters/tartaglia/abil.go
- pkg/core/combat.go
- sim.go
- worker.go
Fixes:
- Hu Tao snapshots taken at wrong frames
- Noelle burst snapshot was incorrect
- Noelle Q frames were wrong
- Tartaglia rQ did not refund energy properly
- Tartaglia Q energy consumption frames were flipped
- No longer track DPS for non-enemy targets
> Bugfixes: Noelle, Hu Tao, Tartaglia, Logging

- internal/characters/kazuha/abil.go
- internal/weapons/claymore/spine/spine.go
- pkg/character/curves/charactercurves.go
- pkg/core/stats.go
- pkg/core/target/attack.go
- pkg/parse/keys.go
- pkg/parse/parseCharLine.go
- scripts/charstat/main.go
fixed kazuha burst dmg timing #135  + beidou ascension subs
> fix kazuha + beidou stats

- imports.go
- internal/characters/aloy/abil.go
- internal/characters/amber/abil.go
- internal/characters/diona/abil.go
- internal/characters/ganyu/abil.go
- internal/characters/gorou/abil.go
- internal/characters/sara/abil.go
- internal/characters/tartaglia/abil.go
- internal/characters/venti/abil.go
- internal/characters/xiao/xiao.go
- internal/weapons/claymore/redhorn/redhorn.go
- pkg/character/stats.go
- pkg/core/combat.go
- pkg/core/target/attack.go
- worker.go
Fixes:
- Xiao NA only went up to 5 (#138)
- Various old logging was too verbose - reduced
- Total DPS per Target for 2+ targets was not working properly
- Aligned bow character weakspot interface - now do not hit weakspots by default (#141)
- Add Redhorn
> Fixes: Xiao NA (#138), Logging, worker.go, Weakspot (#141), Redhorn

- internal/characters/albedo/albedo.go
- internal/characters/bennett/bennett.go
- internal/characters/hutao/abil.go
- internal/characters/noelle/abil.go
- internal/characters/yoimiya/yoimiya.go
- internal/weapons/common/common.go
- pkg/character/stats.go
- pkg/core/target/attack.go
- Albedo A4 EM bonus was wrong
- Noelle Q max burst extension was missing
- Hu Tao Blood Blossom did not work
- React bonus tracking was wrong
> Fixes: Albedo A4, Noelle Q Extension, Hu Tao BB, React Bonus

- cmd/gcsim/.gitignore
- internal/characters/shenhe/abil.go
- internal/characters/shenhe/cd.go
- internal/characters/shenhe/shenhe.go
- internal/characters/shenhe/shenhe_test.go
- pkg/parse/parse_test.go
- sim.go
> fix shenhe cd

- internal/characters/shenhe/abil.go
- internal/characters/shenhe/shenhe.go
- internal/characters/yunjin/abil.go
- internal/characters/yunjin/yunjin.go
Fixes:
- Old Rosaria comments in Shenhe code are removed
- Shenhe and Yun Jin now have tags for buff stacks
- Shenhe burst ICD fixed
- Yun Jin particle travel time updated
- Yun Jin hold level 1 particle counts updated
> Fixes: Shenhe and Yun Jin

- internal/weapons/catalyst/prototype/prototype.go
waiting on evidence for Mona.. ready to merge otherwise
> pamber active char fix

- cmd/gcsim/main.go
- internal/characters/fischl/fischl.go
- internal/characters/ningguang/ningguang.go
- internal/weapons/bow/windblume/windblume.go
> Bugfixes: Documentation, Fischl Frames, Ningguang Particle ICD (Fixes #127), Windblume Ode

- internal/characters/travelergeo/abil.go
- internal/weapons/bow/skyward/skyward.go
- internal/weapons/claymore/sealord/sealord.go
- pkg/core/combat.go
- pkg/core/construct.go
Fixes #158, otherwise see commit messages.
> Bugfixes: Luxurious Sea-Lord, Geo Traveler C4, Logging, Constructs, Skyward Harp

- internal/characters/beidou/abil.go
- internal/characters/fischl/asc.go
- internal/characters/fischl/cons.go
- internal/characters/venti/abil.go
- internal/weapons/common/common.go
> Bugfixes - Snapshot Timing, Venti Q Infusion Timing (#62), Favonius Particle Timing

- internal/weapons/spear/primordial/primordial.go
- internal/weapons/sword/black/black.go
> blacksword and jadespear bugfix

- internal/characters/rosaria/abil.go
someone fell asleep at the wheel
> rosaria burstdot multiplier fix

- internal/characters/diona/frames.go
> fix diona burst frames

- internal/artifacts/viridescent/viridescent.go
- internal/characters/chongyun/abil.go
- internal/characters/kazuha/abil.go
Fixes #186.
Fixes #184 and #165.
> Bugfixes: Kazuha Plunge, Chongyun E, VV in AoE

- cmd/gcsim/main.go
- cmd/gcsim/optimize_substats.go
- worker.go
Currently a completely beta/rough implementation, coded up as a proof of concept.
Performance is currently pretty solid among the configs that I've tested. [This sheet](https://docs.google.com/spreadsheets/d/1ThRAQSCQ0o0kzjyG6bFjYIR98yhGCk32GzlV53PwaQw/edit#gid=0) contains a sampling of the configs that I've tested - so far haven't encountered any issue where this implementation completely bombs out.
Tried a few external optimization packages to evaluate performance, but in the end things ended up too slow with difficult general parameter tuning so I manually implemented a lot of stuff which can be done better.
Please give comments/suggestions - I would be totally ok with changing large chunks of this if possible since it's so ugly...
> Initial attempt at KQM substat optimization implementation

- internal/characters/bennett/bennett.go
- internal/characters/raiden/abil.go
- internal/characters/raiden/raiden.go
- internal/characters/sara/abil.go
- internal/characters/sara/sara.go
- internal/characters/sucrose/cd.go
- internal/weapons/catalyst/thrilling/thrilling.go
- pkg/character/actions.go
- pkg/character/tmpl.go
- pkg/core/character.go
- pkg/core/status.go
- pkg/core/target/mods.go
- pkg/core/target/tasks.go
Not fully complete as a lot of mods are not tracked properly using expiry and are instead loaded at the beginning of the sim, but will probably do those on a rolling basis over time.
> Debug improvements

- internal/characters/keqing/keqing.go
- internal/weapons/bow/elegy/elegy.go
- internal/weapons/catalyst/solar/solar.go
- internal/weapons/claymore/nagamasa/nagamasa.go
- internal/weapons/common/common.go
- internal/weapons/spear/kitain/kitain.go
- internal/weapons/sword/cinnabar/cinnnabar.go
- internal/weapons/sword/festering/festering.go
- internal/weapons/sword/freedom/freedom.go
- Fix C4 Keqing
- Sacrificial: check if character is on-field
- Add checks for skill hold (Elegy, Solar, Kitain, Festering, Freedom, Nagamasa, Cinnabar)
> Check for skill hold on some weapons and fix C4 Keqing

- internal/characters/travelergeo/abil.go
- internal/characters/travelergeo/construct.go
> fix iss 217 - add def geomc burst count

- internal/characters/keqing/abil.go
- internal/weapons/bow/polarstar/polarstar.go
- internal/weapons/sword/mistsplitter/mistsplitter.go
for polarstar mostly just moved the atk buff into AddMod (forgot AddPreDamageMod was dynamic..)
> Fixes mistsplitter, polarstar and keqing burst name

- internal/characters/ayaka/abil.go
- internal/characters/ayaka/ayaka.go
- internal/tmpl/character/actions.go
- pkg/core/character.go
Resolves #274 - Adds Ayaka constellations
> Resolves #274 - Adds Ayaka constellations

- internal/characters/klee/abil.go
- internal/tmpl/action/action.go
- pkg/core/action.go
- pkg/core/core.go
- pkg/parse/keys.go
> Add walk action (#239)

- internal/characters/bennett/bennett.go
- internal/characters/bennett/bennett_test.go
- internal/characters/itto/itto_test.go
- internal/characters/shenhe/shenhe_test.go
- internal/characters/sucrose/sucrose_test.go
- internal/characters/yaemiko/yaemiko_test.go
- internal/testhelper/character.go
- internal/testhelper/profiles.go
- internal/tmpl/player/player.go
> fix bennett self aura; fix minor typo

- internal/eventlog/eventlog.go
- internal/eventlog/eventlog_easyjson.go
- internal/eventlog/eventlog_test.go
- internal/tmpl/status/status.go
> Calc log fix

- internal/characters/raiden/abil.go
- internal/characters/raiden/cons.go
> fix raiden c6 not proccing properly

- pkg/parse/parse.go
> add error if no target set

- internal/artifacts/bolide/bolide.go
- internal/tmpl/shield/ctrl.go
- internal/weapons/catalyst/memory/memory.go
- internal/weapons/claymore/unforged/unforged.go
- internal/weapons/spear/vortex/vortex.go
- internal/weapons/sword/summit/summit.go
- pkg/core/handlers.go
- pkg/simulation/resonance.go
> fix isShielded to check for active char

- internal/artifacts/crimson/crimson.go
- internal/weapons/catalyst/hakushin/hakushin.go
- internal/weapons/sword/freedom/freedom.go
> Fix Freedom-Sworn, CrimsonWitch, Hakushin Ring

- internal/characters/gorou/gorou.go
- internal/characters/kazuha/kazuha.go
- internal/characters/mona/mona.go
- internal/characters/qiqi/qiqi.go
- internal/characters/raiden/raiden.go
- internal/characters/sara/sara.go
- internal/characters/shenhe/shenhe.go
- internal/characters/sucrose/sucrose.go
- internal/characters/travelergeo/travelergeo.go
- internal/characters/xiangling/xiangling.go
- internal/characters/yaemiko/yaemiko.go
- internal/characters/yunjin/yunjin.go
- internal/tmpl/character/curve_test.go
- internal/tmpl/character/tmpl.go
- pkg/core/character.go
- pkg/core/core.go
> fix initial mods added in wrong col

- internal/tmpl/construct/construct.go
- internal/tmpl/queue/conditions.go
- internal/tmpl/queue/construct.go
- pkg/core/construct.go
- pkg/core/handlers.go
fixes #142 
Test file:
[test.gz](https://github.com/genshinsim/gcsim/files/8136350/test.gz)
Link: https://gcsim.app/viewer/share/Ou8Wqmfa8RZ85-H1gv0Gs
> add construct duration and count conditionals

- pkg/core/core.go
- pkg/parse/parseCharLine.go
> trigger err if invalid artifact

- internal/characters/ayaka/abil.go
- internal/characters/ganyu/abil.go
- Add `ayakaci` status for Ayaka's cryo infusion.
Example:
```
ayaka dash +if=.status.ayakaci == 0;
ayaka attack:2, charge;
```
- Add `ganyuburst` status for Ganyu's burst.
Example:
```
sr_seq: sucrose skill;
ay_seq: ayaka dash, burst;
ganyu burst;
chain sr_seq, ay_seq +if=.status.ganyuburst > 0;
```
> Add some statuses.

- internal/weapons/bow/mitternachtswaltz/mitternachtswaltz.go
- pkg/simulation/imports.go
* Add mitternachtswaltz weapon def + import
> Initial mitternachtswaltz

- pkg/core/core.go
- pkg/parse/parseCharLine.go
* trigger err if invalid artifact
* fix err msg
* fix parser not erroring out
redoing #317 so that it gets merged into main instead
> trigger err if invalid artifact (#317)

- internal/characters/gorou/gorou.go
- internal/characters/kazuha/kazuha.go
- internal/characters/mona/mona.go
- internal/characters/qiqi/qiqi.go
- internal/characters/raiden/raiden.go
- internal/characters/sara/sara.go
- internal/characters/shenhe/shenhe.go
- internal/characters/sucrose/sucrose.go
- internal/characters/travelergeo/travelergeo.go
- internal/characters/xiangling/xiangling.go
- internal/characters/yaemiko/yaemiko.go
- internal/characters/yunjin/yunjin.go
- internal/tmpl/character/curve_test.go
- internal/tmpl/character/tmpl.go
- pkg/core/character.go
- pkg/core/core.go
Redoing #325 so it gets merged into main instead
> fix initial mods added in wrong col (#325)

- cmd/gcsim/.gitignore
- internal/characters/kazuha/abil.go
- internal/characters/kazuha/frames.go
- internal/characters/kazuha/kazuha.go
- internal/tmpl/action/action.go
- internal/tmpl/character/actions.go
- internal/tmpl/character/frames.go
- internal/tmpl/character/tmpl.go
- pkg/core/action.go
- pkg/core/cfg.go
- pkg/core/character.go
- pkg/core/core.go
- pkg/parse/parseOptions.go
- pkg/simulation/core.go
- pkg/simulation/run.go
- pkg/simulation/sim.go
* add global custom action based delay
* add human defaults
* frames framework and kazuha frames update
* update kaz hit marks to match kisa count
* clean up unused variables
Redoing #327 so it gets merged into main instead
> custom global delay, frames framework, kazuha frame update (#327)

- internal/artifacts/reminiscence/reminiscence.go
- internal/characters/barbara/abil.go
- internal/characters/barbara/barbara.go
- internal/characters/diona/abil.go
- internal/characters/kokomi/abil.go
- internal/characters/yaemiko/yaemiko.go
- internal/weapons/catalyst/thrilling/thrilling.go
- Add cooldown to 4pc shimenawa
- Fix kokomi skill adding burst bonus if `core.F = 0`
- Fix #353
- Fix #359
- Fix barbara skill consuming energy and proc'ing 4tom
- Fix #360
> Fix barbara, kokomi skill, yaemiko a4, ttds, 4pc shim

- pkg/core/core.go
- pkg/parse/parseOptions.go
human defaults missing frames for aim
> add aim to human defaults

- internal/characters/eula/abil.go
- internal/reactable/swirl.go
- internal/reactable/swirl_test.go
> fix eula icewhirl timing re pale flame, fix swirl applying too much durability in aoe

- pkg/simulation/run.go
```eula char lvl=80/90 cons=0 talent=6,6,6;
eula add weapon="dullblade" refine=1 lvl=1/20;
eula add set="paleflame" count=4;
options mode=sl skill_delay=100;
target lvl=100 resist=.1;
active eula;
eula skill;
eula attack;
eula skill;
```
```
eula char lvl=80/90 cons=0 talent=6,6,6;
eula add weapon="dullblade" refine=1 lvl=1/20;
eula add set="paleflame" count=4;
options mode=apl skill_delay=100;
target lvl=100 resist=.1;
active eula;
eula skill;
eula attack;
```
> fix delay bug #373

- internal/weapons/spear/whitetassel/whitetassel.go
- pkg/simulation/imports.go
> Add whitetassel

- internal/artifacts/exile/exile.go
- internal/substatoptimizer/substatoptimizer.go
- pkg/simulation/imports.go
> Add theexile

- internal/characters/barbara/abil.go
- internal/characters/bennett/bennett.go
- internal/characters/diona/abil.go
- internal/characters/fischl/fischl.go
- internal/characters/gorou/abil.go
- internal/characters/hutao/abil.go
- internal/characters/jean/jean.go
- internal/characters/kaeya/kaeya.go
- internal/characters/kokomi/abil.go
- internal/characters/kokomi/kokomi.go
- internal/characters/noelle/abil.go
- internal/characters/noelle/noelle.go
- internal/characters/qiqi/abil.go
- internal/characters/qiqi/qiqi.go
- internal/characters/zhongli/shield.go
- internal/tmpl/health/health.go
- internal/weapons/catalyst/prototype/prototype.go
- internal/weapons/sword/aquila/aquila.go
- internal/weapons/sword/black/black.go
- pkg/core/handlers.go
- pkg/core/health.go
Weapons:
Talents:
Constellations:
> Refactoring healing system

- internal/weapons/bow/predator/predator.go
- pkg/simulation/imports.go
> Predator Initial

- internal/tmpl/queue/queue.go
- pkg/parse/parseRestart.go
> Add debug line for reset_limit

- internal/characters/ayaka/abil.go
- internal/characters/ganyu/abil.go
- internal/characters/ganyu/ganyu.go
- internal/characters/kazuha/kazuha.go
- internal/characters/ningguang/ningguang.go
- internal/characters/sucrose/abil.go
- internal/characters/sucrose/sucrose.go
- internal/characters/xiangling/xiangling.go
- internal/characters/yaemiko/kitsune.go
- internal/characters/yaemiko/yaemiko.go
- internal/weapons/catalyst/widsith/widsith.go
- pkg/core/events.go
- Resolves #394
- Fix Ganyu A1 applying on first shot
- Fix Ningguang A4 not proc'ing
- Fix Ayaka C1 not checking for element
- Add 1 frame ICD to Kazuha A4
- Add C4 check on Sucrose NA
- Remove OnDash event
- Change Xiangling C6 to use expiry field
- Change Sucrose A1/A4 to use expiry field
- Change widsith to use expiry field
> Fix YaeMiko C4, Sucrose C4, Ganyu A1, Ningguang A4, Ayaka C1 and change some mods to use expiry field

- internal/reactable/electrocharged.go
```
options debug=true iteration=1 duration=112 workers=24 mode=sl;
xingqiu char lvl=80/90 cons=0 talent=6,6,6;
xingqiu add weapon="dullblade" refine=1 lvl=1/20;
xingqiu add set="thunderingfury" count=4;
beidou char lvl=80/90 cons=0 talent=6,6,6;
beidou add weapon="dullblade" refine=1 lvl=1/20;
target lvl=100 resist=0.1;
active beidou;
beidou burst;
xingqiu burst;
xingqiu attack;
wait 40;
xingqiu skill;
```
> ec to emit event on refill

- internal/tmpl/character/tmpl.go
- internal/tmpl/target/mods.go
- pkg/core/character.go
- pkg/core/target.go
the viewer will have to be fixed before this PR can be merged.
the mod handling changes were made to fix the following bug, and to make the mods code consistent.
> Fix mods not being tracked in log

- CONTRIBUTING.md
Found the updated command here: https://docs.gcsim.app/reference/desktop_application
> Fix outdated command.

- internal/weapons/bow/amos/amos.go
- internal/weapons/bow/elegy/elegy.go
- internal/weapons/bow/favonius/favonius.go
- internal/weapons/bow/sacrificial/sacrificial.go
- internal/weapons/bow/stringless/stringless.go
- internal/weapons/catalyst/favonius/favonius.go
- internal/weapons/catalyst/sacrifical/sacrificial.go
- internal/weapons/catalyst/thrilling/thrilling.go
- internal/weapons/claymore/favonius/favonius.go
- internal/weapons/claymore/sacrifical/sacrificial.go
- internal/weapons/spear/favonius/favonius.go
- internal/weapons/spear/homa/homa.go
- internal/weapons/sword/favonius/favonius.go
- internal/weapons/sword/sacrifical/sacrificial.go
> Add some alternate weapon names.

- internal/artifacts/archaic/archaic.go
- internal/artifacts/huskofopulentdreams/huskofopulentdreams.go
- internal/artifacts/viridescent/viridescent.go
- internal/characters/kazuha/abil.go
- internal/characters/sara/abil.go
- internal/substatoptimizer/substatoptimizer.go
- internal/tmpl/event/events.go
- internal/weapons/catalyst/moonglow/moonglow.go
- internal/weapons/claymore/redhorn/redhorn.go
- internal/weapons/sword/alley/alley.go
- internal/weapons/sword/cinnabar/cinnnabar.go
- pkg/parse/parseCharLine.go
- pkg/parse/parseOptions.go
- Cleanup Sara A4/C1 code
- Resolve #413
> Fix Kazuha burst, Sara burst and Moonglow scaling

- internal/weapons/catalyst/moonglow/moonglow.go
> Fix Moonglow scaling for other characters

- internal/characters/diona/abil.go
- internal/characters/kaeya/kaeya.go
- internal/characters/klee/abil.go
- internal/characters/rosaria/rosaria.go
- internal/characters/sara/abil.go
- internal/characters/tartaglia/abil.go
- internal/characters/tartaglia/tartaglia.go
the energy log change in genshinsim/gcsim.app#54 broke the viewer for some configs.
config: https://gcsim.app/viewer/share/uuydGakKqdZ-cd4iiJSxZ
> Remove energy logs from character code

- internal/artifacts/echoes/echoes.go
- internal/artifacts/vermillion/vermillion.go
- internal/characters/venti/abil.go
these were unveiled in 2.6 livestream
> 2.6 artifacts implementation

- internal/characters/ayato/abil.go
- pkg/simulation/run.go
fixes ayato skill -> attack delay as well
> fix delay too long by 1f

- internal/artifacts/viridescent/viridescent.go
- internal/reactable/electrocharged.go
- internal/reactable/freeze.go
- internal/reactable/overload.go
- internal/reactable/reactable.go
- internal/reactable/superconduct.go
- internal/reactable/swirl.go
- add em to swirl attacks
- prevent 4vv from adding bonus in vape
> fix swirl vape bug:

- internal/characters/kazuha/abil.go
- internal/characters/kazuha/kazuha.go
- internal/characters/sucrose/abil.go
- internal/characters/sucrose/sucrose.go
- internal/characters/venti/abil.go
- internal/characters/venti/venti.go
- internal/tmpl/player/player.go
- pkg/core/element.go
fixes venti picking up pyro infuse from bennett self infusion due to infusion check not having an aoe check
> absorb check to check collision

- cmd/wasm/main.go
- pkg/core/cfg.go
- pkg/core/charkey.go
- pkg/core/element.go
- pkg/parse/parse.go
- pkg/parse/parseCharLine.go
- pkg/parse/parse_test.go
- Change parser to preserve character ordering from config file
- Add custom JSON marshaling for CharKey and EleType
- Add parser error if character have more than 5 artifacts
- Add parser error if more than 4 characters in a team
> update parser and improve JSON output

- internal/characters/noelle/abil.go
- internal/characters/noelle/frames.go
- internal/characters/noelle/noelle.go
- internal/characters/noelle/noelle_test.go
based on [this sheet](https://docs.google.com/spreadsheets/d/1fpJmJ7SylDkrb0-ghuAnUc977Lf6yH-uWpOmyvazFNM/edit?usp=sharing), missing frames for
- `attack` -> `charge`
- `attack` -> `walk`
- `charge` -> `x`
> Update Noelle frames

- internal/characters/lisa/abil.go
- internal/characters/lisa/frames.go
* Fix [Issue #431](https://github.com/genshinsim/gcsim/issues/431)
* Adjust starting burst action frames
* Quick test [here](https://gcsim.app/viewer/share/cOMnYS8wnHkNgOwrMfvh0)
> bugfix(lisa burst)

- internal/characters/ayaka/abil.go
- internal/characters/ayaka/ayaka.go
- internal/characters/ayaka/frames.go
- pkg/core/core.go
- Implements recounted ayaka frames
- Frames taken from [this spreadsheet](https://docs.google.com/spreadsheets/d/1WPxQ7vf0_dp5g96aqGF0_JZSqjtYHOJC0b89zRS_WrA/edit?usp=sharing), and were counted by me from @k0l11's [video](https://www.youtube.com/watch?v=ulTSQRrR4n8)
- Could use a few more tests to make sure it's implemented properly, but has worked fine in the tests I've run so far
- Tested here: https://gcsim.app/viewer/share/perm_6D0Pnrw-HG_l-I8_Vq88H
> ayaka frames update

- internal/reactable/reactable.go
> changing melt/vape check order

- internal/tmpl/character/helper.go
- internal/tmpl/queue/conditions.go
- internal/tmpl/queue/counter.go
- pkg/core/character.go
> Add counter

- pkg/simulation/characters.go
test: https://gcsim.app/viewer/share/perm_TgmDeJsmBD8jcdHmKigk0
> fix max level

- internal/characters/albedo/albedo.go
- internal/characters/ayaka/abil.go
- internal/characters/kazuha/abil.go
- internal/characters/ningguang/abil.go
- internal/characters/ningguang/ningguang.go
- internal/tmpl/character/tmpl.go
- internal/tmpl/status/status.go
- Fix kazuha swirling his absorb dot
> Change Albedo and Ningguang Blossoms/Gems to use skill snapshot

- internal/artifacts/huskofopulentdreams/huskofopulentdreams.go
- internal/characters/ayato/abil.go
- internal/characters/diluc/abil.go
- internal/characters/diluc/diluc.go
- internal/characters/ganyu/abil.go
- internal/characters/keqing/abil.go
- internal/characters/keqing/frames.go
- internal/characters/keqing/keqing.go
- internal/characters/xiangling/xiangling.go
- Fix diluc/keqing skill not working with CD reduction buffs
- Fix keqing skill not setting cooldown correctly
- Resolve #491
- Resolve #487
> Fix ayato/ganyu burst, keqing/diluc skill and husk set stacks

- internal/characters/jean/frames.go
- internal/characters/jean/jean.go
- internal/characters/jean/jean_test.go
- Updates Jean frames
- Implements stamina on Jean's CAs
- Sheet: https://docs.google.com/spreadsheets/d/1KQB8VOEyaCsRa3QulF-gAq3a1CxsqiauTNYuK2_paMY/edit?usp=sharing
- Video: https://youtu.be/HJrJkYgsg84
- Tested here: https://gcsim.app/viewer/share/perm_QVchWKeioaMIr6dhfc4ts
> jean frames update

- internal/characters/eula/abil.go
- internal/characters/eula/eula.go
- internal/characters/eula/eula_test.go
- internal/characters/eula/frames.go
based on [this sheet](https://docs.google.com/spreadsheets/d/1NCDFtvqFdXlVRd_0eH2tPw7xMD50AxUCvbWDh1XGhEw/edit)
> Update Eula frames

- internal/characters/rosaria/abil.go
- internal/characters/rosaria/frames.go
- internal/characters/rosaria/rosaria.go
- internal/characters/rosaria/rosaria_test.go
- Updates Rosaria frames
- Sheet: https://docs.google.com/spreadsheets/d/1buBVBvlgfNcRA09XA3BLm-oA7hpCVRYkGt_7kPBYJu0/edit?usp=sharing
- Video: https://youtu.be/_FVJTwjKW4A
- Tested here: https://gcsim.app/viewer/share/perm_S-sT6hknFCEeI6kQiABZr
> rosaria frames update

- internal/characters/keqing/abil.go
- internal/characters/keqing/frames.go
- internal/characters/keqing/keqing.go
- Updates Keqing frames
- Sheet (by @k0l11): https://docs.google.com/spreadsheets/d/1GAeBzMr0XX89azZhpbjEqPfehgruwI3__GlfEgQ1VvA/edit#gid=775340159
- Videos: https://youtu.be/kI6N3Mn5BQY and https://youtu.be/9xe2nygCtKE
- Tested here: https://gcsim.app/viewer/share/perm_DGiEzI6vaaS7UJxN3PoLZ
> keqing frames update

- internal/characters/zhongli/abil.go
- internal/characters/zhongli/frames.go
- internal/characters/zhongli/zhongli.go
- internal/characters/zhongli/zhongli_test.go
- Updates Zhongli frames
- Sheet: https://docs.google.com/spreadsheets/d/1NPOothWseChb-OzOHQqunBdi-M3udmQPqPop0kf7H-w/edit?usp=sharing
- Videos: https://youtu.be/2TMxz446akc and https://youtu.be/tb1bGGVNJoA
- Tested here: https://gcsim.app/viewer/share/perm_2NLa7nr0egEcYdvErdkwJ
> zhongli frames update

- internal/characters/diluc/abil.go
- internal/characters/diluc/diluc.go
- internal/characters/diluc/frames.go
- Updates Diluc frames
- Sheet (by @k0l11): https://docs.google.com/spreadsheets/d/1p0blrnuM7JvwU2QMdZdLayYqP3-7OMDgYC6GDQNn_QU/edit#gid=547671271
- Video: https://youtu.be/KsBKdqCPFj8 
- Tested here: https://gcsim.app/viewer/share/perm_yoi78MzPVlFGorZqh6XZt
> diluc frames update

- internal/characters/xiao/abil.go
- internal/characters/xiao/frames.go
- internal/characters/xiao/xiao.go
- internal/tmpl/action/action.go
- internal/tmpl/character/actions.go
- pkg/core/character.go
- pkg/core/core.go
- pkg/core/events.go
- pkg/core/state.go
- Updates Xiao frames
- Implements Jump as an overridable action
- Changes Xiao plunge combo syntax from "high_plunge" to "jump, high_plunge"
- Changes Xiao plunge parameter from "plunge_hits" to "collision" and limits it to 1 additional hit
- Sheet: https://docs.google.com/spreadsheets/d/1WHJy9UjCQY0AO32yluJMhX_ecGO1KGb6SjbOZt9VJDg/edit#gid=775340159
- Videos: https://youtu.be/oadNODbooZQ and https://youtu.be/tb1bGGVNJoA?t=174
- Tested here: https://gcsim.app/viewer/share/perm_QcjBcHwrqUUk3P15_aPNy
> xiao frames update

- internal/characters/ganyu/abil.go
- internal/characters/ganyu/frames.go
- internal/characters/ganyu/ganyu.go
- internal/characters/ganyu/ganyu_test.go
- Updates Ganyu frames
- Sheet: https://docs.google.com/spreadsheets/d/1PDHCZKh-7eWpbE1b0OyQUCzSPHcViYZ22EDEItjiU7Y/edit?usp=sharing
- Video: https://youtu.be/ROvivlCUR3s
- Tested here: https://gcsim.app/viewer/share/perm_GXx-UDeQ3chtpj8UvH8_6
> ganyu frames update

- internal/characters/ayaka/abil.go
- Fixes a bug where Ayaka A1 was not applying to CAs.
> fix ayaka a1

- internal/artifacts/scholar/scholar.go
- pkg/simulation/imports.go
Scholar set 2PC and 4PC implementation: links for testing below:
- https://gcsim.app/viewer/share/b2X3jLb30PRAnXRy4tDsN
Proccing only for those with catalyst or bow
- https://gcsim.app/viewer/share/arMZOyVzvhQiLKXsytK0C
Proccing only if the user that has the set gets the particle
Inspiration from exile set
> Scholar set implementation

- internal/artifacts/gambler/gambler.go
- pkg/simulation/imports.go
- Adds Gambler artifact set
- 4pc effect not included, e-bots only
- Tested here: https://gcsim.app/viewer/share/perm_49q7_061AyjmxHfYnn0xh
> add gambler

- internal/weapons/catalyst/mappa/mappa.go
https://www.youtube.com/watch?v=l8Q8LTAR4kQ
> fix mappa stacks

- internal/characters/beidou/abil.go
- internal/characters/beidou/beidou.go
- internal/characters/beidou/frames.go
- Updates Beidou frames
- Sheet: https://docs.google.com/spreadsheets/d/1r8fwU2wMBbZsy5fqqSSf8aLvX8aFvJCvaDD8P3Lr2sI/edit?usp=sharing
- Video: https://youtu.be/mCDHSI1JhuI
- Tested here: https://gcsim.app/viewer/share/perm_oJoY52dmDHCgm92sE_IX0
> beidou frames update

- internal/characters/kokomi/abil.go
- internal/characters/kokomi/frames.go
- internal/characters/kokomi/kokomi.go
sheet: https://docs.google.com/spreadsheets/d/1j3Hzo25qSqo-ZbQBiBqcejR1aa91igSVTxH1xoKYrfc/edit
> Update Kokomi frames

- internal/characters/amber/amber.go
- internal/characters/yoimiya/abil.go
- internal/characters/yoimiya/frames.go
- internal/characters/yoimiya/yoimiya.go
- internal/characters/yoimiya/yoimiya_test.go
- Updates Yoimiya frames
- Sheet: https://docs.google.com/spreadsheets/d/1DYYiGSNeFekVt3eQQC_MujkLCd_8rgPIIlpPNvwHKTA/edit?usp=sharing
- Video: https://www.youtube.com/watch?v=UNo3Q-DPmbM
- Tested here: https://gcsim.app/viewer/share/perm_II8f_U5mns98K06fPrlB-
> yoimiya frames update

- internal/substatoptimizer/substatoptimizer.go
Fixes https://github.com/genshinsim/gcsim/issues/474
> fix substat optimizer

- internal/characters/xiao/abil.go
> Changed Xiao E ICD, default ICD -> Xiao E ICD

- internal/characters/ningguang/abil.go
resolves #551 
also added star jade update in the debug
> Fix Ningguang A1

- internal/reactable/reactable.go
Moved tryFrozenSuperconduct to happen before tryAddEC
fix #557
> Fixed Issue 557

- internal/characters/lisa/abil.go
- internal/characters/lisa/frames.go
- internal/characters/lisa/lisa.go
- internal/characters/lisa/lisa_test.go
- Updates Lisa frames
- Sheet: https://docs.google.com/spreadsheets/d/1KRt6I_c5qeUQVXcHv7ZOZKdqjn4Z_VN1OyVFvhDumOc/edit?usp=sharing
- Videos: https://youtu.be/f58tVgt3OYw and https://youtu.be/WiQ20bQejuw
- Tested here: https://gcsim.app/viewer/share/perm_fc0AvivUZU0WufswLqd2F
> Lisa frames update

- internal/characters/kazuha/abil.go
- kazu c6 infusion now properly only activates at c6
- add c6 infusion to burst cast
> fix kazu c6 infusion check and activate on burst

- internal/weapons/bow/twilight/twilight.go
https://gcsim.app/viewer/share/perm_cF80JZ-dO3qVKnFKMFZn9
Tested, applying the buff as intended, assumed dynamic
> fixed twilight weapon bug

- internal/characters/keqing/abil.go
> fix keqing a1 infusion start

- internal/weapons/sword/coolsteel/coolsteel.go
- pkg/simulation/imports.go
> Implement cool steel

- internal/characters/yelan/frames.go
- internal/characters/yelan/yelan.go
> Add Yelan aim cancels

- internal/characters/yelan/abil.go
Adressing issue #584
Tested here:
https://gcsim.app/viewer/share/perm_hYrXmaFbosGsvWzxu_srd
> fix yelan c4

- internal/characters/lisa/abil.go
As according to Issue #265, random targetting on burst has been implemented
C4 still needs implementation
> Fixed Lisa targetting on burst

- internal/characters/yelan/abil.go
- pkg/core/icd.go
fixes #601
viewer file here: https://gcsim.app/viewer/share/perm_AfmfyRL_SeU-YmD-TqwUP
> fix iss601 yelan c6

- internal/characters/itto/abil.go
This fixes effects like Itto's C6 not applying to his own charge attacks.
> Fix multiple Itto issues

- internal/characters/zhongli/abil.go
> Fix invalid zhongli steele replacement

- internal/characters/heizou/skill.go
https://discord.com/channels/845087716541595668/983391844631212112/998217839058096158
> Fix stacks from A1 (heizou)

- internal/characters/heizou/burst.go
- internal/characters/heizou/frames.go
- internal/characters/heizou/skill.go
- pkg/core/icd.go
Heizou frame update, Srl, please check the part 2 commit, I think the return at the end on skill function must be "f,a" instead "return skillChargeStart + dur + f, a" for the cancels to work?
> Heizou frames update

- README.md
"hesistate" -> "hesitate"
No issue reference because problem is too small to justify an issue.
> Fix spelling issue in README.md

- internal/characters/qiqi/attack.go
- internal/characters/qiqi/burst.go
- internal/characters/qiqi/charge.go
- internal/characters/qiqi/skill.go
video(s): https://youtu.be/56yh-6WqN-I + https://youtu.be/tb1bGGVNJoA?t=68
sheet: https://docs.google.com/spreadsheets/d/1uS_n16mlfdfzjBiVG3w6TmR9H7YqSSFOoyox_9bn-Kk/edit?usp=sharing
also:
- rename e buff key
> Qiqi frames update

- pkg/conditional/conditional.go
- pkg/conditional/onfield.go
- pkg/gcs/ast/node.go
- fix copy default case (https://discord.com/channels/845087716541595668/983391844631212112/1006676091328540672)
- add `onfield` condition:
| field1     | field2           | field3 | field4 | description
| ---        | ---              | ---    | ---    | ---
| `onfield`  | `any char name`  | none   | none   | is the char on the field
example: https://next.gcsim.app/v3/viewer/share/c404e10f-7c30-449a-be26-f0ffbd08bfd3
> gcs bugfix

- internal/characters/albedo/attack.go
- internal/characters/albedo/burst.go
- internal/characters/albedo/charge.go
- internal/characters/albedo/skill.go
video(s): https://youtu.be/BYr-3R-XpfE + https://youtu.be/tb1bGGVNJoA
sheet: https://docs.google.com/spreadsheets/d/1WIejtwUZpZ2lqTNlK2_6cJPoDe0PUmCL6QKB05m_AQQ/edit?usp=sharing
> Albedo frames update

- internal/characters/aloy/aimed.go
- internal/characters/aloy/attack.go
- internal/characters/aloy/burst.go
- internal/characters/aloy/skill.go
video: https://youtu.be/mGnzKSsvq9s
sheet: https://docs.google.com/spreadsheets/d/11uyES6x6UFGm2bqcsY4dPSqLgsELrdkPv145NmMwTmc/edit?usp=sharing
also:
- adds travel parameter for skill
- fixes Q not snapshotting (see https://library.keqingmains.com/evidence/characters/cryo/aloy#burst-mechanics)
> Aloy frames update

- internal/characters/diona/aimed.go
- internal/characters/diona/attack.go
- internal/characters/diona/burst.go
- internal/characters/diona/skill.go
video: https://youtu.be/iPphkHE5U5g
sheet: https://docs.google.com/spreadsheets/d/178Y92g19FlBIb1hIPHKvjByk_NztZ7854pjkkt4fEV4/edit?usp=sharing
also:
- changes diona burst status name to "diona-q"
- adjusts burst field start (affects DoT start and C6 start)
> Diona frames update

- internal/characters/amber/aimed.go
- internal/characters/amber/attack.go
- internal/characters/amber/burst.go
- internal/characters/amber/skill.go
video: https://youtu.be/UrChJbc4juc
sheet: https://docs.google.com/spreadsheets/d/1XDS-RP7G7-htZ4PP9A5SXPbg7Gy-Laksp4oXwObNgf8/edit?usp=sharing
> Amber frames update

- internal/characters/chongyun/attack.go
- internal/characters/chongyun/burst.go
- internal/characters/chongyun/cons.go
- internal/characters/chongyun/skill.go
video: https://youtu.be/BjgV0LkDUpA
sheet: https://docs.google.com/spreadsheets/d/13TsDRmuHCrXBKlka-huhKt1xtjNHhLEZIuJJzj1OQvg/edit?usp=sharing
also:
- fixes c4 icd not being affected by hitlag
> Chongyun frames update

- internal/characters/kaeya/attack.go
- internal/characters/kaeya/burst.go
- internal/characters/kaeya/charge.go
- internal/characters/kaeya/skill.go
video(s): https://youtu.be/RvgMyM9f3Gk + https://youtu.be/tb1bGGVNJoA?t=56
sheet: https://docs.google.com/spreadsheets/d/11f_FxKhXFpL4EHSfFHPPjhXJvVOTi-FP_R6cqaZ9dwo/edit?usp=sharing
> Kaeya frames update

- internal/characters/yunjin/attack.go
- internal/characters/yunjin/burst.go
- internal/characters/yunjin/charge.go
- internal/characters/yunjin/skill.go
video(s): https://youtu.be/dIlxs5zi1e0 + https://youtu.be/tb1bGGVNJoA?t=201
sheet: https://docs.google.com/spreadsheets/d/1rDQZ8TJd6JAzD3C6pg_JZrgkYr-LIp36mmXE8XVMj4s/edit?usp=sharing
also:
- adjust q status name
> Yun Jin frames update

- internal/characters/yaemiko/attack.go
- internal/characters/yaemiko/burst.go
- internal/characters/yaemiko/charge.go
- internal/characters/yaemiko/kitsune.go
- internal/characters/yaemiko/skill.go
video: https://youtu.be/UUcbZDh4oIA
sheet: https://docs.google.com/spreadsheets/d/1G8_pp_NFtM1wteo_xRZaG-lTcS3NZ1vADVmjFFp_SOk/edit?usp=sharing
> Yae frames update

- internal/characters/xinyan/attack.go
- internal/characters/xinyan/burst.go
- internal/characters/xinyan/cons.go
- internal/characters/xinyan/skill.go
- internal/characters/xinyan/xinyan.go
video: https://youtu.be/PT7BQuZAVTE
sheet: https://docs.google.com/spreadsheets/d/1Wz7gtnavp5pzNjSFidi0EFluZ4E8CoaogvzOXSEF3-E/edit?usp=sharing
also:
- adjust some names
- fix multiple different shield DoTs co-existing
> Xinyan frames update

- internal/characters/sara/aimed.go
- internal/characters/sara/attack.go
- internal/characters/sara/burst.go
- internal/characters/sara/skill.go
video: https://youtu.be/omTcYawTD8U
sheet: https://docs.google.com/spreadsheets/d/1B29Zceb_pl8FYfHtIrZeMttZtovmwE8tHEZud_kkbmo/edit?usp=sharing
also:
- adjust e cover name
> Sara frames update

- internal/characters/shenhe/attack.go
- internal/characters/shenhe/burst.go
- internal/characters/shenhe/charge.go
- internal/characters/shenhe/cons.go
- internal/characters/shenhe/shenhe.go
- internal/characters/shenhe/skill.go
- Fix burst initial hit ICD and StrikeType
- Change burst shred and A1/C2 to apply every 18 frame on active char
sheet: https://docs.google.com/spreadsheets/d/1CeCbNYTXozBDeeRerGJFLWwsKrKz3K3-PydNSBATx8E/edit
video: https://youtu.be/27cpC8A_elw
> Update shenhe frames

- internal/characters/razor/attack.go
- internal/characters/razor/burst.go
- internal/characters/razor/skill.go
video: https://youtu.be/CUXnqF1S2ps
sheet: https://docs.google.com/spreadsheets/d/1Rceie6ATwNDSbnmIIKgZa1cVtXlBZE6earpJb42SHAM/edit?usp=sharing
also:
- adjust q status name
> Razor frames update

- internal/characters/mona/asc.go
- internal/characters/mona/attack.go
- internal/characters/mona/burst.go
- internal/characters/mona/charge.go
- internal/characters/mona/dash.go
- internal/characters/mona/skill.go
video(s): https://youtu.be/KfjCdGrh5Dk + https://youtu.be/mRSPMhmpKX0
sheet: https://docs.google.com/spreadsheets/d/1fCdmkNZ6vXmqiOmk6s0Q8AQFzOQt_UjltspbMyDrx4A/edit?usp=sharing
also:
- implements hold e and a1
- fixes a bug where e ticked 1 more time than it should
> Mona frames update

- internal/characters/sayu/asc.go
- internal/characters/sayu/attack.go
- internal/characters/sayu/burst.go
- internal/characters/sayu/cons.go
- internal/characters/sayu/skill.go
video: https://youtu.be/w7YDOFDuVC0
sheet: https://docs.google.com/spreadsheets/d/1vLH6ZiAhb7G-f5ecYy-sPLoCdouA5krMixtgh9ITX2Q/edit?usp=sharing
also:
- adjust naming for various instances of dmg in E
- add short hold e
- fix DoT Elemental DMG on Hold E wrongly using scaling for Kick Elemental DMG
> Sayu frames update

- internal/characters/noelle/asc.go
- internal/characters/noelle/attack.go
- internal/characters/noelle/burst.go
- internal/characters/noelle/noelle.go
- internal/characters/noelle/skill.go
> fix noelle hitlag

- services/dbmanage/Dockerfile
- services/docker-compose.yml
- services/embed/Dockerfile
Fix docker file for embed and db bot service
> fix dockerfile

- internal/characters/eula/skill.go
> fix eula hold e particle gen

- internal/artifacts/paleflame/paleflame.go
- internal/characters/eula/burst.go
- fix eula q status duration lasting longer than it should
- fix eula q status earliest point
- fix pale flame never getting more than 1 stack because of statmod name mistake
- add logging to pale flame stack gain
> eula & pale flame bug fixes

- internal/characters/yoimiya/aimed.go
sheet: https://docs.google.com/spreadsheets/d/1DYYiGSNeFekVt3eQQC_MujkLCd_8rgPIIlpPNvwHKTA/edit?usp=sharing
- implements `yoimiya aim`
- fixes #207
> implement yoimiya aim

- internal/characters/yoimiya/burst.go
- internal/characters/yoimiya/cons.go
- internal/characters/yoimiya/yoimiya.go
also:
- adjust q status and icd name
> fix yoimiya q hitlag

- internal/characters/heizou/asc.go
- internal/characters/heizou/attack.go
- internal/characters/heizou/charge.go
- internal/characters/heizou/cons.go
- internal/characters/heizou/heizou.go
- internal/characters/heizou/skill.go
- adjust placeholder hitlag values
- a1/c1 icd should be affected by hitlag
- make it easier to see if a used E has max stacks in debug
- fix unnecessary char queue calls
> fix heizou hitlag

- internal/characters/ayato/cons.go
also:
- rename C6 attack so it's easier to see in debug
> fix ayato c6 hitlag

- internal/characters/jean/burst.go
- ticked for 11 times instead of 10
- was missing In/Out dmg on field expiry
> fix jean q

- internal/characters/kuki/asc.go
- internal/characters/kuki/attack.go
- internal/characters/kuki/burst.go
- internal/characters/kuki/charge.go
- internal/characters/kuki/cons.go
- internal/characters/kuki/kuki.go
- internal/characters/kuki/skill.go
video: https://youtu.be/kbdvX4Oy-u0
sheet: https://docs.google.com/spreadsheets/d/1cXejpod69F6HReq6jztxEvlpVzSGKssz5NNHIzqY4QY/edit?usp=sharing
> Kuki frames update and hitlag 

- internal/characters/albedo/charge.go
albedo ca shouldn't have any hitlag
> fix albedo ca hitlag

- pkg/core/energy.go
previous values didn't match the wiki
https://genshin-impact.fandom.com/wiki/Energy#Energy_Generated_by_Normal_Attacks
> fix na/ca energy probabilities

- internal/characters/gorou/aimed.go
- internal/characters/gorou/attack.go
- internal/characters/gorou/burst.go
- internal/characters/gorou/cons.go
- internal/characters/gorou/gorou.go
- internal/characters/gorou/skill.go
video: https://youtu.be/pOJnyO91pQ8
sheet: https://docs.google.com/spreadsheets/d/15eKpg9ii86ufny24TEZgzWT0xQbzmIfMUCA2fktuaB4/edit?usp=sharing
also:
- fix naming scheme
- fix c4 being tied to skill instead of burst
- adjust buff/duration start for e/q (fixes #211)
> Gorou frames update

- internal/characters/barbara/attack.go
- internal/characters/barbara/burst.go
- internal/characters/barbara/charge.go
- internal/characters/barbara/dash.go
- internal/characters/barbara/skill.go
Frame fixes based off the sheet in #209 .
> Barbara frame adjustment

- internal/characters/zhongli/attack.go
fixes #719 
video: https://youtu.be/diz7tQf8-yY
sheet: https://docs.google.com/spreadsheets/d/19dQSj8Y8LJ_2kLgWKPlkNp9y7sqvFiquO5h03R2YNXI/edit?usp=sharing
> fix zhongli n5 frames

- internal/characters/ganyu/aimed.go
- internal/characters/ganyu/burst.go
- internal/characters/ganyu/cons.go
- internal/characters/ganyu/ganyu.go
- internal/characters/ganyu/skill.go
spelling mistake made ganyu c4 not work
> fix ganyu c4 spelling mistake and adjust constellation names

- internal/characters/bennett/burst.go
Players should not get the bennett buff if they are out of range.
> Add bennett buff range check

- pkg/optimization/details.go
Some of the debug messages were leftover from testing.
> Remove extra optimizer output

- internal/characters/barbara/skill.go
- adds missing deployable hitlag
- adds missing melody loop ticks (1.5s timer)
- fixes barbara e duration start and tick start
- fixes self wet being an attack instead of a self infusion
- combines heal and self wet ticks into one function
- adjusts barbara e status name
> fix and rewrite barbara e

- internal/characters/thoma/attack.go
- internal/characters/thoma/burst.go
- internal/characters/thoma/charge.go
- internal/characters/thoma/shield.go
- internal/characters/thoma/skill.go
- internal/characters/thoma/thoma.go
Fixes thoma frames based off the post in #209 .
> Thoma frame adjustment

- services/embed/scripts/embed.py
Fixed issue with incorrect artifact placement when one or more characters did not have any sets at all.
Also updated character that are 2pc + rainbow to only show half of the aritfact.
> Fixed incorrect artifacts in embed

- pkg/gcs/expr.go
issue: https://discord.com/channels/845087716541595668/884485336657444894/1009208235636563969
example: https://next.gcsim.app/v3/viewer/share/7194e565-8e2c-4342-801e-0b8d31b2a094
> implement unary expressions

- pkg/conditional/conditional.go
- pkg/conditional/cons.go
example: https://next.gcsim.app/v3/viewer/share/f87ed6c3-9752-46ad-b6e1-046a8b955c16
```
let c1 = .cons.kokomi >= 1;
fn kokoatk(c, max) {
kokomi attack:2;
if c1 { kokomi attack; }
if c != max {
kokomi dash;
kokoatk(c+1, max);
}
}
```
| field1     | field2                | field3 | field4 | description
| ---        | ---                   | ---    | ---    | ---
| `cons`   | `any char name`       | none   | none   | get char cons
> add cons condition

- internal/weapons/sword/amenoma/amenoma.go
The 30s duration is hitlag extendable.
> Add hitlag extension to amenoma seed expiry

- internal/characters/yoimiya/asc.go
- internal/characters/yoimiya/attack.go
- internal/characters/yoimiya/skill.go
- internal/characters/yoimiya/yoimiya.go
Also includes some refactors involving char statuses.
> fix yoimiya normal attack icd

- pkg/gcs/ast/node.go
- pkg/gcs/ast/parse.go
- pkg/gcs/repl/repl.go
- pkg/gcs/stmt.go
slightly different implementation than #740. change else to be a general stmt instead of using an array of ifs
> else if implementation

- internal/characters/albedo/skill.go
> fix cons coniditons

- internal/characters/barbara/skill.go
- internal/characters/heizou/heizou.go
- internal/characters/kaeya/kaeya.go
- internal/characters/kazuha/kazuha.go
- internal/characters/razor/razor.go
- pkg/simulation/setup.go
> stamina bugfixes - sprint utility passive, anemo res stam reduction, barbara a1

- internal/characters/fischl/fischl.go
> expose fischl oz duration as conditional

- pkg/simulation/setup.go
Hydro resonance change in 3.0 per Hoyoverse patch notes: https://genshin.hoyoverse.com/en/news/detail/23126
> 3.0 hydro res change

- internal/characters/raiden/skill.go
closes #657 
- make eye + eye dmg buff start at hitmark
- remove the raidenskill status because the eye dmg buff status can be reused (eye should also be hitlag extendable)
- eye dmg icd is not affected by hitlag
- eye only procs if the eye buff status is active on the char whose dmg is proccing the eye
TODO:
> adjust raiden e mechanics

- README.md
the readme was looking a bit outdated but i'm not 100% sure what to type since i am not a developer, someone should rephrase what is needed for the future of gcsim
> Readme update?

- internal/characters/yanfei/asc.go
originally from raph#2041 on discord: https://discord.com/channels/845087716541595668/869210750596554772/1013807607867244706
> fix wrong yanfei a4 condition

- internal/characters/itto/asc.go
- internal/characters/itto/attack.go
- internal/characters/itto/burst.go
- internal/characters/itto/charge.go
- internal/characters/itto/cons.go
- internal/characters/itto/itto.go
- internal/characters/itto/skill.go
- internal/characters/itto/ushi.go
Redo of #663 based on current `main`.
> Cleanup itto code

- internal/artifacts/gildeddreams/gildeddreams.go
- should work off-field
- buff duration should be affected by hitlag
- should have an 8s icd which is also affected by hitlag
> fix gildeddreams

- internal/characters/fischl/burst.go
> fix fischl C4 naming convention

- internal/characters/itto/charge.go
fixes #868 
tested here: https://gcsim.app/v3/viewer/share/6b93aeac-2b70-42ab-aec7-5189ce22bf08
> fix itto c6

- .github/workflows/preview.yml
Made a typo in the preview.yml branch name
> fix deploy branch name

- internal/characters/yaemiko/charge.go
Technically does not match dm, but this is essentially ICDTagNone in game.
> fix yaemiko charge ICD and durability

- app/src/Components/Character/CharacterCard.tsx
- app/src/Components/Character/Stats.ts
- app/src/Pages/Sim/helper.ts
- app/src/util.ts
- pkg/core/attributes/stats.go
Dendro SVG is missing since I'm not sure how @srliao sourced them. Threvax sent me some SVGs but they're not in the same format as webapp.
> fix dendro not showing properly on web

- cmd/gcsim/main.go
https://discord.com/channels/845087716541595668/884485336657444894/1009970948943908984
> serve to hhtp link fix

- internal/characters/kokomi/burst.go
> fix kokomi a1 timing

- internal/characters/xingqiu/burst.go
> fix xingqiu c6 energy regen in multitarget

- internal/characters/xiao/cons.go
- internal/characters/xiao/xiao.go
> implement xiao c4

- internal/artifacts/paleflame/paleflame.go
- internal/characters/chongyun/cons.go
- internal/characters/keqing/cons.go
- internal/characters/lisa/skill.go
- internal/characters/ningguang/attack.go
- internal/characters/rosaria/cons.go
- internal/characters/yanfei/attack.go
- internal/weapons/bow/prototype/prototype.go
- internal/weapons/bow/viridescent/viridescent.go
- internal/weapons/catalyst/dodoco/dodoco.go
- internal/weapons/catalyst/frostbearer/frostbearer.go
- internal/weapons/catalyst/skyward/skyward.go
- internal/weapons/catalyst/solar/solar.go
- internal/weapons/claymore/nagamasa/nagamasa.go
- internal/weapons/claymore/pines/pines.go
- internal/weapons/claymore/prototype/prototype.go
- internal/weapons/claymore/sealord/sealord.go
- internal/weapons/claymore/skyrider/skyrider.go
- internal/weapons/claymore/starsilver/starsilver.go
- internal/weapons/claymore/whiteblind/whiteblind.go
- internal/weapons/claymore/wolf/wolf.go
- internal/weapons/spear/dragonspine/dragonspine.go
- internal/weapons/spear/skyward/skyward.go
- internal/weapons/sword/flute/flute.go
- internal/weapons/sword/prototype/prototype.go
- based on https://docs.google.com/spreadsheets/d/1S_Toll_6qIO1q2ood0KPteVH0-lw3mAPTKqEkmJeo9U/edit?usp=sharing
> fix missing on-field checks

- internal/characters/albedo/burst.go
- internal/characters/aloy/burst.go
- internal/characters/ayaka/burst.go
- internal/characters/ayato/burst.go
- internal/characters/barbara/burst.go
- internal/characters/diluc/burst.go
- internal/characters/eula/burst.go
- internal/characters/ganyu/burst.go
- internal/characters/hutao/burst.go
- internal/characters/itto/burst.go
- internal/characters/jean/burst.go
- internal/characters/kazuha/burst.go
- internal/characters/keqing/burst.go
- internal/characters/klee/burst.go
- internal/characters/kokomi/burst.go
- internal/characters/mona/burst.go
- internal/characters/qiqi/burst.go
- internal/characters/raiden/burst.go
- internal/characters/shenhe/burst.go
- internal/characters/tartaglia/burst.go
- internal/characters/venti/burst.go
- internal/characters/xiao/burst.go
- internal/characters/yaemiko/burst.go
- internal/characters/yelan/burst.go
- internal/characters/yoimiya/burst.go
- internal/characters/zhongli/burst.go
based on https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
video: https://youtu.be/KlgZlck5kQQ
TODO:
> replace cam cancel burst frames

- internal/characters/collei/burst.go
- internal/characters/collei/skill.go
https://discord.com/channels/845087716541595668/869210750596554772/1016669863080636487
> fix missing cons check for collei c4 & c6

- internal/artifacts/braveheart/braveheart.go
- internal/characters/albedo/skill.go
- internal/characters/ayato/cons.go
- internal/characters/chongyun/cons.go
- internal/characters/diluc/cons.go
- internal/characters/eula/cons.go
- internal/characters/heizou/burst.go
- internal/characters/razor/cons.go
- internal/characters/xiangling/guoba.go
- internal/characters/yanfei/cons.go
- pkg/core/combat/absorb.go
- pkg/core/combat/attack.go
- pkg/core/combat/target.go
- pkg/enemy/attack.go
- pkg/enemy/enemy.go
- pkg/gadget/gadget.go
- pkg/target/target.go
Checked vs this one: https://dendro.gcsim.app/v3/viewer/share/afd2568b-8ac0-4d0c-945d-a21d8655acd0
DPS is the same so should be an no op change. Have not tested the individual chars though that I fixed
> refactor target interface and add basic gadget

- internal/artifacts/thunderingfury/thunderingfury.go
- pkg/reactable/catalyze.go
> Add Aggravate and Hyperbloom bonus to 4TF

- .gitignore
- services/assets/Dockerfile
- services/assets/main.go
- services/docker-compose.yml
- services/worker/src/assets/index.ts
- services/worker/src/bindings.d.ts
- services/worker/src/index.ts
Centralized server to handle all the assets so that everything share the same images (and fix issue with missing images etc...)
> add assets server

- pkg/result/results.go
Preview: https://gcsim.app/v3/viewer/share/4b307aea-7226-458c-9d0d-19c538c78622
> show duration stats in detail page

- pkg/gcs/ast/item.go
- pkg/gcs/ast/keys.go
- pkg/gcs/ast/lex_test.go
- pkg/gcs/ast/node.go
- pkg/gcs/ast/parse.go
- pkg/gcs/ast/parse_test.go
- pkg/gcs/stmt.go
syntax:
```go
for <init>; <cond>; <post> { <body> }
```
records:
```go
for let x = 0; x < 5; x = x + 1 { } // from 0 to 4
for { } // infinity loop
for ;; { } // infinity loop
```
example: https://gcsim.app/v3/viewer/share/87ad61cd-89d4-4279-873b-372fc752b0ec
> add for statement

- internal/weapons/common/goldenmajesty.go
originally from Rare Possum#0511: https://discord.com/channels/845087716541595668/869210750596554772/1021726905981997056
> fix golden majesty series not getting more than 1 stack

- internal/characters/ayato/attack.go
video: https://youtu.be/AL2qAaaIvhs
sheet: https://docs.google.com/spreadsheets/d/1opwMTQdDAHuzP1y6Sx1iN874p2aC0tlzNngzNKOXvIk/edit?usp=sharing
TODO:
> add ayato nx -> ca cancel frames

- internal/characters/diluc/diluc.go
- internal/characters/diluc/skill.go
via Charliex3000#9403 from discord: https://discord.com/channels/845087716541595668/869210750596554772/1021493420914638859
> diluc e window should be hitlag extendable

- pkg/core/combat/icd.go
- pkg/core/event/event.go
- pkg/enemy/attack.go
- pkg/enemy/hitlag.go
- pkg/reactable/burning.go
- pkg/reactable/burning_test.go
- pkg/reactable/reactable.go
TODO in this PR:
TODO in later PR:
> implement burning

- internal/characters/hutao/attack.go
- internal/characters/hutao/charge.go
based on the existing sheet: https://docs.google.com/spreadsheets/d/1KR_FMtupIbLEhWRGww2N2UKEJG3hy5mWJIez8S6EZ2w/edit?usp=sharing
changes (now the frames follow what I said to use in my sheet):
E N2: 17 -> 16 
E CA out of E N1: 2 -> 1 if next is dash, 2 if next is jump
E CA out of E N2: 5 -> 4 if next is dash, 5 if next is jump
> adjust hu tao e n2 and e ca frames

- internal/characters/xiangling/guoba.go
- internal/tests/reactable/bloom_test.go
- internal/tests/reactable/dendrocore_test.go
- pkg/conditional/conditional.go
- pkg/conditional/gadgets.go
- pkg/core/combat/combat.go
- pkg/core/combat/combat_test.go
- pkg/core/combat/gadget.go
- pkg/core/combat/gadget_test.go
- pkg/gadget/gadget.go
- pkg/reactable/bloom.go
continuation of the PR here: https://github.com/genshinsim/gcsim/pull/963
changed it so that the limit is enforced by core and force gadgets to have types. should make it easier for future gadgets that also have limits
> update bloom limit - max 5

- db/src/Components/Cards/CharacterCard.tsx
my very critical contribution for the month
> change db card chars to white text

- db/src/App.tsx
> Add whitespace to db warning

- internal/characters/diluc/attack.go
- internal/characters/diluc/diluc.go
- internal/characters/diluc/skill.go
> add diluc c6 implementation

- internal/characters/xiao/asc.go
- internal/characters/xiao/burst.go
- internal/characters/xiao/xiao.go
> refactor xiao a1 into modifier

- internal/weapons/sword/prototype/prototype.go
> fix prototype rancour stack reset

- internal/characters/yanfei/yanfei.go
yanfei now has a field `seal-count` that will return the number of seals active
> add seal count field to yanfei

- db/src/App.tsx
adjust db warning to tell users that it is not a dps leaderboard.
based on discussion here: https://discord.com/channels/845087716541595668/1006934337612173413/1032717676830801930.
not 100% sold on my wording, open to suggestions on the best way to phrase it
> update db warning

- pkg/enemy/enemy.go
- pkg/target/icd.go
- pkg/target/target.go
Pulling out the code by @Charlie-Zheng from #877
> Refactor out icd handling from enemy

- pkg/reactable/bloom.go
- pkg/reactable/burning.go
- pkg/reactable/catalyze.go
- pkg/reactable/crystallize.go
- pkg/reactable/electrocharged.go
- pkg/reactable/freeze.go
- pkg/reactable/melt.go
- pkg/reactable/overload.go
- pkg/reactable/reactable.go
- pkg/reactable/superconduct.go
- pkg/reactable/swirl.go
- pkg/reactable/vaporize.go
Created separate based on changes in #877 by @Charlie-Zheng
> Expose try functions in reactable

- internal/artifacts/thunderingfury/thunderingfury.go
- internal/characters/cyno/cons.go
- internal/characters/dori/asc.go
- internal/characters/fischl/asc.go
- internal/characters/kazuha/asc.go
- internal/characters/keqing/cons.go
- internal/characters/sayu/asc.go
- internal/characters/sucrose/asc.go
- internal/characters/tighnari/cons.go
- internal/characters/yunjin/cons.go
- internal/weapons/catalyst/emeraldorb/emeraldorb.go
- internal/weapons/catalyst/hakushin/hakushin.go
- internal/weapons/sword/darkironsword/darkironsword.go
- pkg/simulation/setup.go
Separated out from #877 by @Charlie-Zheng
> Fix reaction gadget check

- internal/artifacts/viridescent/viridescent.go
- internal/characters/qiqi/burst.go
- internal/characters/tartaglia/riptide.go
- internal/characters/yelan/skill.go
- pkg/enemy/attack.go
- pkg/enemy/damage.go
- pkg/enemy/hitlag.go
- pkg/reactable/reactable_test.go
- pkg/target/icd.go
- pkg/target/target.go
Remove old references to target index that shouldn't be used anymore
> fix target index should not be used

- pkg/reactable/bloom.go
- pkg/reactable/burning.go
- pkg/reactable/catalyze.go
- pkg/reactable/crystallize.go
- pkg/reactable/electrocharged.go
- pkg/reactable/freeze.go
- pkg/reactable/melt.go
- pkg/reactable/overload.go
- pkg/reactable/reactable.go
- pkg/reactable/superconduct.go
- pkg/reactable/swirl.go
- pkg/reactable/vaporize.go
force the various try functions in reactable to return true for reacted. allows for easier override when using reactables
> add bool return to try functions

- pkg/core/player/character/basestat.go
Traveler elements were getting overridden to NoElement.
Note that Traveler needs to set ele manually in the character creation
> fix traveler always set to wrong ele

- app/yarn.lock
Fixing yarn file to fix deployment build in mainline
> Fixed yarn lock file

- internal/weapons/catalyst/skyward/skyward.go
> fix skyward atlas ticks, logging, aoe and add travel param

- internal/characters/nilou/bountifulcore.go
- pkg/reactable/bloom.go
- pkg/reactable/burning.go
- pkg/reactable/electrocharged.go
- pkg/reactable/freeze.go
- pkg/reactable/overload.go
- pkg/reactable/reactable.go
- pkg/reactable/superconduct.go
- pkg/reactable/swirl.go
> refactor calcReactionDmg to create snapshot for calc logs

- internal/characters/jean/burst.go
- internal/characters/jean/cons.go
> fix jean c4 timing

- internal/characters/keqing/skill.go
> fix keqing c1 dmg order

- pkg/core/construct/handler.go
fixes #1050 
tested here: https://gcsim.app/v3/viewer/share/b272597c-56cd-4aed-979e-531d70e21213
> fix geo construct order not resetting on construct refresh

- internal/characters/nilou/asc.go
> fix nilou a1 em

- pkg/shortcut/characters.go
> add candace into character shortcuts

- internal/characters/nahida/cons.go
> remove nahida c4 todo

- internal/characters/heizou/heizou.go
> add declension stack conditional to heizou

- pkg/conditional/enemy.go
Sometimes this is useful for figuring out the remaining durability on a target in order to time reactions.
> change .element to output element durability

- internal/weapons/catalyst/fruitoffulfillment/fruitoffulfillment.go
- pkg/shortcut/weapons.go
- pkg/simulation/imports.go
part of #1091 
stack loss logic is based on 4 piece husk
> add fruit of fulfillment

- internal/weapons/bow/kingssquire/kingssquire.go
- pkg/simulation/imports.go
> add king's squire

- pkg/reactable/electrocharged.go
> fix ec not getting rejected when target is frozen

- pkg/core/attributes/element_map.go
- pkg/core/player/player.go
- pkg/enemy/enemy.go
- pkg/gcs/ast/parser.go
- pkg/result/results.go
- pkg/simulator/simulator.go
- ui/packages/executors/src/WasmExecutor.ts
- ui/packages/types/src/sim.ts
- ui/packages/ui/src/Pages/Viewer/Viewer.tsx
Added additional information to .json output, for example relevant simulator settings or target data.
> Additional information for .json output

- internal/characters/albedo/skill.go
- internal/characters/ayaka/cons.go
- internal/characters/candace/cons.go
- internal/characters/eula/burst.go
- internal/characters/gorou/cons.go
- internal/characters/nilou/cons.go
- internal/weapons/bow/predator/predator.go
- internal/weapons/bow/skyward/skyward.go
- internal/weapons/bow/thundering/thundering.go
- internal/weapons/common/favonius.go
- internal/weapons/common/royal.go
- internal/weapons/common/sacrificial.go
- internal/weapons/spear/crescent/crescent.go
- internal/weapons/sword/filletblade/filletblade.go
- internal/weapons/sword/skyward/skyward.go
- internal/weapons/sword/swordofdescension/swordofdescension.go
- pkg/enemy/damage.go
also fixes the crit bool getting set to 0 when calced dmg is 0. attacks which end up having 0 dmg can still crit.
> fix certain abilities proccing on attacks that deal 0 dmg

- internal/characters/nahida/cons.go
https://discord.com/channels/845087716541595668/869210750596554772/1048585405823471646
> fix nahida c6 not being able to proc off-field

- pkg/shortcut/characters.go
I'm the head honcho of the Arataki Gang, and everyone knows my name...s. Names, I have many. Arataki "The One and Oni" Itto
Arataki "The Oni Sumo King" Itto
Arataki "The Pride of Oni" Itto
Arataki "Beetle Gladiator" Itto
Arataki "The Ultimate TCG Champion" Itto
Arataki "He Might Lose but He'll Never Admit Defeatto"... Anyway, these are some of the ones I usually go by, so go ahead, take your pick. I'll respond to whichever one you choose, I promise. Hehe, you're welcome.
> add Arataki ''The One and Oni'' Itto as "shortcut"

- internal/artifacts/echoes/echoes.go
- internal/characters/ayato/ayato.go
- internal/weapons/bow/hunterspath/hunterspath.go
- internal/weapons/claymore/redhorn/redhorn.go
- internal/weapons/sword/cinnabar/cinnnabar.go
> fix flat dmg wrongly using snapshotted stats

- internal/characters/candace/skill.go
- internal/characters/yunjin/skill.go
> add shield names for candace and yunjin

- internal/characters/raiden/burst.go
> fix raiden resolve stacks snapshotting on burst cast

- internal/weapons/bow/slingshot/slingshot.go
> fix slingshot affecting tartaglia riptide flash/blast and melee NA/CAs

- pkg/target/icd.go
> fix damage and elemental ICD index wrapping

- internal/characters/traveleranemo/asc.go
- internal/characters/traveleranemo/traveleranemo.go
Fixes #1103 .
EDIT: sample config https://gcsim.app/v3/viewer/share/9213b206-08b0-4efb-a4d9-ec6caae63b15.
> add traveleranemo a4

- internal/characters/barbara/attack.go
> fix incorrect barbara frames on N4

- internal/tests/reactable/hyperbloom_test.go
- pkg/reactable/bloom.go
> adjust hyperbloom travel time and dendro core spawn delay

- internal/characters/nilou/bountifulcore.go
- pkg/reactable/bloom.go
> fix bloom core hurtbox radius

- internal/characters/amber/burst.go
- pkg/core/player/character/basestat.go
- pkg/core/player/character/profile/profile.go
> Refactor Amber Q Hit Logic and Add Ascension to CharacterBase

- internal/characters/hutao/burst.go
now the only condition for her to apply Blood Blossoms with her burst is "if c.Base.Cons >= 2"
"c.StatModIsActive(paramitaBuff)" condition removed
> C2 Hutao burst fix

- internal/tests/collision/collision_test.go
- pkg/core/combat/combat_test.go
- pkg/core/combat/rectangle.go
> Readjusted rect calcs to use true center

- internal/characters/sayu/burst.go
- pkg/core/player/player.go
- the hp check should use active char, not lowest hp char in party 
- targeting and needAttack/needHeal didn't properly account for c1
> fix sayu q logic

- internal/weapons/catalyst/tulaytullahsremembrance/tulaytullahsremembrance.go
Should last for the full duration of the sim.
> fix tulaytullahsremembrance atkspd duration

- internal/characters/albedo/burst.go
> fix albedo q snapshot, a4 and c2 timing

- internal/characters/raiden/burst.go
> fix raiden c4 timing not being affected by hitlag

- internal/characters/kazuha/burst.go
> fix kazuha c2 timing

- internal/characters/amber/amber.go
- internal/characters/amber/bunny.go
- internal/characters/amber/cons.go
> fix amber c2 being mv instead of dmg%

- internal/weapons/bow/recurve/recurve.go
> add recurve bow passive

- internal/characters/sara/burst.go
should start at 6 + 1.35 = 7.35m instead of 1.35m
> fix sara q stormcluster pos

- pkg/reactable/freeze.go
- pkg/reactable/freeze_test.go
- pkg/reactable/reactable.go
https://discord.com/channels/845087716541595668/869210750596554772/1070342766158155856
> fix freeze durability calculation

- internal/characters/ningguang/ningguang.go
> fix ningguang star jades not getting reset on swap

- internal/weapons/bow/elegy/elegy.go
- internal/weapons/claymore/pines/pines.go
- internal/weapons/common/millennial.go
- internal/weapons/sword/freedom/freedom.go
> fix stacking of millennial buffs of same type

- internal/characters/kazuha/kazuha.go
bug: https://discord.com/channels/845087716541595668/869210750596554772/1076523930740867092
> initialize element for kazuha a1

- internal/characters/chongyun/skill.go
https://discord.com/channels/845087716541595668/869210750596554772/1077221893574234153
> fix crash when chongyun uses a skill without c4

- internal/characters/fischl/fischl.go
- internal/characters/fischl/skill.go
Also fixes Oz's spawn position in preparation of a future A1/projectile implementation.
> fix fischl oz hitbox snapshotting on summon

- internal/weapons/sword/freedom/freedom.go
Fixed Freedom Sworn granting universal damage bonus instead of NA/CA/P, and granting ATK% as NA/CA/P bonus
> Fixed Freedom Sworn Passive

- internal/characters/dori/burst.go
bug: https://discord.com/channels/845087716541595668/884485336657444894/1080466581030699118
> fix hitbox for the connector (dori burst)

- internal/weapons/claymore/beacon/beacon.go
- pkg/core/curves/weaponcurves.go
- pkg/core/keys/weapon.go
- pkg/shortcut/weapons.go
- pkg/simulation/imports.go
needs the on damage mechanic
has a parameter for stacks as a workaround
> beacon initial implementation

- internal/characters/kokomi/cons.go
bug: https://discord.com/channels/845087716541595668/869210750596554772/1083513475910860820
> fix kokomi c4 (worked without burst)

- app/package.json
- app/src/Pages/Sim/Components/ActionList.tsx
- app/yarn.lock
* Updating to latest version of syntax highlighting (all characters added since v1.9)
* Fixed editor font to be Fira Mono
> Fixed editor font and updated prismjs

- internal/characters/jean/charge.go
- internal/characters/kaeya/charge.go
- internal/characters/kuki/charge.go
- internal/characters/qiqi/charge.go
- internal/characters/xingqiu/charge.go
Moved Jean's CA ICD to part of her Normal Attacks
> fixed Jean CA ICD

- internal/characters/eula/skill.go
- internal/characters/fischl/asc.go
Fixed Eula's Shred not applying to secondaries.
> Fixed Eula's AoE Shred on Hold E

- internal/characters/nilou/skill.go
bug: https://discord.com/channels/845087716541595668/869210750596554772/1094168198368206928
> fix nilou particle generation

- internal/characters/mika/attack.go
currently the program crashes when mika does N2
> fix mika normal attacks

- app/src/Data/character_data.json
added nilou and nahida and fixed a few keys
> hotfix for enka update to 3.5

- internal/artifacts/vorukashasglow/vorukashasglow.go
Stacks is the number of permanent vorukasha stacks a character will have. Stacks will only be added if the counter reaches a missing stack, rather than always adding more stacks.
> add stacks param for vorukashasglow

- internal/characters/baizhu/asc.go
Now it properly adds to burning damage
> Baizhu a4 fix

- internal/characters/baizhu/skill.go
Now he is generating 4 particles 50% of the time as it should be
> Fixed Baizhu's energy generation on skill

- pkg/core/player/heal.go
previously it only logged the heal amount before multiplying with healing bonus
> fix heal logging

- internal/characters/yaemiko/attack.go
- internal/characters/yaemiko/charge.go
- pkg/core/attacks/icd.go
> fix yae na and ca hitboxes

- internal/characters/chongyun/skill.go
Delayed Chongyun's Field creation to the same frame as hit hitmark.
fixes #1344
> Delayed chongyun's skill field until hitmark

- internal/characters/diluc/burst.go
- internal/characters/thoma/burst.go
- `dot` and `explode` param are now deprecated
> fix diluc q hitbox

- internal/characters/baizhu/attack.go
- internal/characters/baizhu/burst.go
- internal/characters/baizhu/charge.go
- internal/characters/baizhu/cons.go
- internal/characters/baizhu/skill.go
- internal/common/normalattackstate.go
- pkg/result/check.go
- fixes baizhu e not ticking more than once in single target
- fixes baizhu q healing on very first tick
> baizhu frames + bugfixes

- internal/weapons/catalyst/perception/perception.go
now does:
- 1 target: 1 attack
- 2 targets: 2 attacks
- 3 targets: 3 attacks
- 4+ targets: 5 attacks
before it was 5 attacks for all cases
> fix eye of perception implementation

- internal/characters/jean/burst.go
Fixed Jean not consuming energy when bursting
> Fixed Jean Energy

- internal/characters/albedo/cons.go
- internal/characters/baizhu/asc.go
- internal/characters/chongyun/skill.go
- internal/characters/dori/cons.go
- internal/characters/ganyu/burst.go
- internal/characters/kaveh/cons.go
- internal/characters/travelerdendro/asc.go
- internal/characters/travelerelectro/cons.go
- internal/characters/travelerelectro/skill.go
- internal/weapons/spear/primordial/primordial.go
- pkg/simulation/setup.go
major:
- pjws (5s -> 6s, now hitlag extendable)
minor (now hitlag extendable):
- albedo c4
- baizhu a4
- chongyun c2
- dori c4 er
- ganyu a4
- kaveh c1
- dmc a1
- emc c2 
- emc amulet er
- geo resonance
> various duration fixes

- pkg/core/action/failure.go
> fix deceased spelling

- internal/characters/xiangling/guoba.go
> fix sucrose/faruzan e durability against guoba

- internal/weapons/claymore/mailedflower/mailedflower.go
OnSkill -> OnEnemyDamage with normal/hold e check
> fix mailedflower trigger not being skill dmg

- pkg/core/attacks/icd.go
> change icd var initialization

- internal/artifacts/gildeddreams/gildeddreams.go
- internal/artifacts/instructor/instructor.go
- internal/characters/nahida/nahida.go
- internal/characters/qiqi/asc.go
- internal/tests/reactable/burning_test.go
- internal/weapons/catalyst/fruitoffulfillment/fruitoffulfillment.go
- internal/weapons/catalyst/mappa/mappa.go
- internal/weapons/claymore/mailedflower/mailedflower.go
- internal/weapons/spear/missive/missive.go
- internal/weapons/sword/freedom/freedom.go
- pkg/core/event/event.go
related to #124
As of 3.7, only Nahida E and Mailed Flower consider Shatter as an elemental reaction when it comes to triggering on "all" reactions.
> fix shatter in all reaction event subs

- internal/characters/heizou/cons.go
- internal/characters/heizou/skill.go
slight change in snapshot timing is fine (~2f)
> change heizou c6 from expiry -1

- pkg/reactable/electrocharged.go
closes #1221 
- can only happen via hydro -> quicken + electro
live: https://gcsim.app/v3/viewer/share/4fbef7db-be2d-40a1-ab01-34e5aa285282 (hydro + electro remaining, 2 ec ticks)
pr: https://gcsim.app/v3/viewer/share/69c361d4-fb14-425e-9ea2-375904b85e2a (only electro remaining, 1 ec tick)
> fix hydro/electro attaching after bloom for ec

- cmd/gcsim/main.go
closes #1398 
Workflow to get a .gz viewer file for a given config in combination with the substat optimizer:
before:
```
./gcsim.exe -c="test.txt" -substatOptim -out="test_opt.txt"
./gcsim.exe -c="test_opt.txt" -gz -out=test
```
after:
```
./gcsim.exe -c="test.txt" -substatOptimFull -gz -out=test
```
key differences:
- before: create a file holding the optimized config under "test_opt.txt"
- after: overwrite the content of the original config file "text.txt" to contain the optimized config
If the user wants to adjust substats after running the new workflow, they can simply adjust the config file and run the sim again, but this time without the `-substatOptimFull` flag.
The old workflow is still available.
> add substatOptimFull flag to cli

- ui/packages/db/package.json
- ui/packages/db/src/App.tsx
- ui/packages/db/src/Pages/Database/DBVIew.tsx
- ui/packages/db/src/Pages/Database/Database.tsx
- ui/packages/db/src/Pages/Database/index.ts
- ui/packages/db/src/Pages/TagDatabase.tsx
- ui/packages/db/src/SharedComponents/FilterComponents/Filter.utils.ts
- ui/packages/db/src/SharedHooks/databaseQuery.ts
- ui/yarn.lock
change pagination to infinite scroll on db
TODO: really server should respond back if there are more data... right now this relies on sort of a hacky solution
> database infinite scroll

- ui/packages/ui/src/Pages/Sample/Components/SampleView.tsx
Make sample search case insensitive
resolves #597
> make sample search case insensitive

- ui/packages/docs/src/components/Fields/data.json
- ui/packages/docs/src/components/Frames/data.json
- ui/packages/docs/src/components/Params/data.json
> update docs for itto

- ui/packages/docs/docs/reference/characters/travelerdendro.md
- ui/packages/docs/src/components/Frames/data.json
forgot them when I was adding missing char docs
> add docs for travelerdendro

- ui/packages/docs/docs/reference/characters/heizou.md
- ui/packages/docs/src/components/Fields/data.json
- ui/packages/docs/src/components/Hitlag/data.json
- ui/packages/docs/src/components/Params/data.json
Also update the checksum for our Prism repo since I was getting "The remote archive doesn't match the expected checksum"
> add docs for heizou

- ui/packages/docs/src/components/Params/data.json
was added back by mistake during merging of all the docs prs
> remove deleted albedo param

- ui/packages/docs/src/components/Frames/data.json
recorded in the [video](https://youtu.be/tb1bGGVNJoA) but not counted/used:
- ayaka
- jean 
- raiden
- rosaria
- xingqiu
> add n1 -> ca related video links to docs 

- internal/characters/amber/cons.go
bugged due to wrong logical operator
> fix amber c2 applying to every bunny

- ui/packages/docs/src/components/Frames/data.json
taken from the [sheet](https://docs.google.com/spreadsheets/d/1R_OywCjjSW8PeYPPniBLVnoTZ8uQ2L_GLKYmQvFTHV0/edit?usp=sharing) / [playlist](https://www.youtube.com/playlist?list=PLkHHjV6Ul8L0UVhekzN7pjRLQr9m876rZ) (some videos like the ones at positions 9-14 are for uncanceled actions and thus not relevant)
> add missing videos to barbara docs

- ui/packages/docs/docs/guides/character_builder.md
- ui/packages/docs/docs/guides/sample_configs.md
- ui/packages/docs/docs/mechanics/reactions.md
If any of these should be added back, then create an issue for them. I personally think only the reactions page is really needed, so I created an issue for it (#1513).
> remove empty pages from docs

- ui/packages/docs/docs/guides/understanding_config_files.md
- ui/packages/docs/docs/reference/config.md
mainly adding `for`, `continue` and `break` to gcsl docs
> update gcsl related docs

- ui/packages/docs/docs/reference/config.md
> remove frozen and quicken from config target docs

- internal/characters/mika/charge.go
- ui/packages/docs/src/components/Hitlag/HitlagTable.js
- ui/packages/docs/src/components/Hitlag/character_data.json
internal:
- fix mika ca not being deployable
> add missing hitlag to docs

- ui/packages/docs/docs/mechanics/atk_spd.md
> add Animation Speed to game mechanics docs

- ui/packages/docs/docusaurus.config.js
> add algolia search bar to docs

- internal/artifacts/desertpavilionchronicle/config.yml
> fix desert pav artifact id

- ui/packages/ui/src/Data/artifact_data.generated.json
forgot to update artifact data.... in #1581
> update artifact data

- pkg/agg/reaction/reaction.go
- pkg/model/result.pb.go
- pkg/simulator/imports.go
- protos/model/result.proto
- ui/packages/types/src/protos.d.ts
- ui/packages/types/src/sim.ts
- ui/packages/ui/src/Pages/Viewer/Components/Miscellaneous/SourceReactionsBarChart/BarChart.tsx
- ui/packages/ui/src/Pages/Viewer/Components/Miscellaneous/SourceReactionsBarChart/index.tsx
- ui/packages/ui/src/Pages/Viewer/Tabs/Results.tsx
> add back reaction count per source statistic

- internal/characters/itto/asc.go
- internal/characters/itto/charge.go
https://discord.com/channels/845087716541595668/1136697299242856499
- left/right and stack count moved to character log
before:
after:
> adjust itto ca combo slash abil name

- ui/packages/ui/src/Pages/Sample/Components/SampleOptions.ts
- ui/packages/ui/src/Pages/Sample/Components/parse.ts
https://discord.com/channels/845087716541595668/1084079367103201351
- move user log category being available from advanced to being available from simple
- move hitlag log category being available from debug to being available from verbose
> adjust log category presets

- internal/weapons/bow/ibispiercer/config.yml
- internal/weapons/catalyst/jadefallssplendor/config.yml
- internal/weapons/claymore/beacon/config.yml
- internal/weapons/claymore/mailedflower/config.yml
- ui/packages/ui/src/Data/weapon_data.generated.json
https://discord.com/channels/845087716541595668/845087716541595671/1136703391377137798
> add missing weapon pipeline data for weapon select

- pkg/core/player/character/profile/profile.go
> add zone for fontaine to char profile

- ui/packages/docs/src/components/Params/character_data.json
- add missing params to character docs (fischl, yelan)
- remove outdated hutao param from docs
> update character param docs

- backend/docker/mosquitto/docker-entrypoint.sh
hopefully fixes mqtt not starting on deploy....
> add -c to mqtt entry point

- internal/characters/traveler/anemo/aether/config.yml
- internal/characters/traveler/dendro/aether/config.yml
- internal/characters/traveler/electro/aether/config.yml
- internal/characters/traveler/geo/aether/config.yml
- ui/packages/db/src/Data/char_data.generated.json
- ui/packages/ui/src/Data/char_data.generated.json
should fix GO/Enka import issues for male traveler variants
> fix male traveler ids in config

- ui/packages/web/public/wasm_exec.js
> update wasm_exec.js due to go version upgrade

- internal/weapons/bow/songofstillness/songofstillness.go
- internal/weapons/catalyst/flowingpurity/flowingpurity.go
- internal/weapons/claymore/tidalshadow/tidalshadow.go
- internal/weapons/spear/rightfulreward/rightfulreward.go
- internal/weapons/sword/finaleofthedeep/finaleofthedeep.go
> fix new weapon merge conflicts

- pkg/simulation/run.go
making recursive calls by accident when it shouldn't be
> fix statefn issue

- internal/characters/alhaitham/burst.go
based on https://discord.com/channels/845087716541595668/884485336657444894/1145095263636176926
- frame 3: q start
- frame 186: n1 starts out phys 
- frame 187: n1 becomes dendro infused
187-3=184 -> changing 190 to 184
> adjust alhaitham q mirror gain timing

- ui/packages/db/src/Pages/Database/DBVIew.tsx
- ui/packages/db/src/SharedComponents/DBEntryView.tsx
- ui/packages/db/src/SharedComponents/DBEntryViewComponents/DBEntryPortrait.tsx
- ui/packages/db/src/SharedComponents/DBEntryViewComponents/DBEntryTags.tsx
- ui/packages/db/src/index.css
- ui/packages/tailwind.config.cjs
- ui/packages/ui/src/Translation/locales/English.json
- Minor improvements to mobile view: add dps information
- Add author information
> db entry improvements

- ui/packages/db/src/SharedComponents/DBEntryView.tsx
> fix db desc not wrapping

- internal/characters/lyney/lyney.go
- ui/packages/docs/src/components/Fields/character_data.json
https://discord.com/channels/845087716541595668/1146930307971416094
syntax: `.lyney.propSurplusStacks`
> expose lyney prop surplus stack count as condition

- ui/packages/docs/docusaurus.config.js
- ui/packages/web/index.html
According to here: https://community.cloudflare.com/t/beacon-min-js-blocked-by-cors/346833/11 this should fix the CORS issue? maybe...
> try fixing cloudflare insight cors issue

- ui/packages/ui/src/Pages/Viewer/Components/Overview/Metadata/DevBuild.tsx
makes it more obvious that the shown sim is based on a local, unofficial build
> change unsigned to unofficial for clarity

- pkg/reactable/bloom.go
- dendro core spawn, expiry and killed via gadget limit
- hyperbloom/burgeon trigger
sim: https://gcsim.app/db/GQHGLq9kGzRB
before:
after:
> add bloom logs for better sample readability

- internal/characters/ganyu/aimed.go
- ui/packages/docs/src/components/Params/character_data.json
- should be 18f instead of 24f
- no param because bloom travel is always the same
> fix ganyu bloom travel

- ui/packages/ui/src/Pages/Simulator/Components/GOOD/parseFromGOOD.ts
this will import any traveler as both lumine and aether with their corresponding element
> fix GO traveler import

- ui/packages/ui/src/Pages/Viewer/Tabs/Sample.tsx
- ui/packages/ui/src/Pages/Viewer/Viewer.tsx
moved up redux dependency out of Sample into viewer to allow Sample to work standalone without dependency on global state tree
> minor Sample code refactor

- internal/characters/kazuha/burst.go
> Fixed Kazuha Q aura check time

- internal/weapons/spear/primordial/primordial.go
Fix PJWS not removing DMG% after losing stacks
> Fix PJWS not falling off

- internal/artifacts/marechausseehunter/marechausseehunter.go
check current active character(drain + heal)
> Fix 4 Marechaussee Hunter trigger off-field

- pkg/core/player/player.go
> Adjust anim/hitlag tick order

- pkg/simulation/run.go
Fix delay getting cut short or the sim throwing an error if a character is hitlagged when delay is executed.
> Fix delay behavior when hitlag is involved

- internal/characters/dehya/cons.go
- internal/characters/kaveh/cons.go
- internal/characters/traveler/common/dendro/asc.go
- internal/weapons/catalyst/eternalflow/eternalflow.go
- internal/weapons/catalyst/tulaytullahsremembrance/tulaytullahsremembrance.go
- infinite duration does not need hitlag
> adjust base of mods with expiry -1

- internal/characters/bennett/burst.go
https://discord.com/channels/845087716541595668/1182152659453616139
1st tick shouldn't heal
> fix bennett q 1st tick triggering healing

- pkg/simulation/run.go
* Fix delay executing an action when it is not ready
- only affect chars that implement their own `ActionReady` logic
* Bring back the logs for when delay is executed
occurs if an action is unavailable after delay is executed. a config to replicate the bug:
```
keqing skill;
delay(300);
keqing skill;
```
> Fix delay executing an action when it is not ready

- ui/packages/ui/src/Components/Cards/CharacterCard.tsx
- ui/packages/ui/src/Pages/Simulator/Components/CharacterCardView.tsx
- ui/packages/ui/src/Pages/Simulator/Components/TeamBuilder/Builder.tsx
> add back red x button to remove char on sim page

- internal/characters/hutao/cons.go
closes #1734
https://discord.com/channels/845087716541595668/1167692515017760788
- first check was at t=2s before
> fix hutao c6 check not starting at t=0s

- ui/packages/docs/docs/reference/system_functions.md
> add docs for delay system function

- internal/characters/freminet/freminet.go
- internal/characters/furina/furina.go
- internal/characters/lynette/lynette.go
- internal/characters/lyney/lyney.go
- internal/characters/neuvillette/neuvillette.go
- internal/characters/traveler/common/hydro/travelerhydro.go
- pkg/core/player/character/character.go
- needed for swordofnarzissenkreuz
> add arkhe flag to charwrapper

- ui/packages/ui/src/Pages/Viewer/Components/Overview/TargetInfo/EnemyCard.tsx
https://discord.com/channels/845087716541595668/1126091239624822835
> fix incorrect phys resist in UI

- ui/packages/docs/src/components/Actions/ActionsTable.js
forgot to make an adjustment in #1783
> fix legal actions table not being adjusted for normal -> attack fix

- pkg/core/core.go
- pkg/core/player/character/character.go
- pkg/core/player/player.go
- ui/packages/docs/docs/reference/config.md
https://discord.com/channels/845087716541595668/1179821680042983494
- works additively with start_hp
> add start_hp% option to starting hp

- internal/weapons/catalyst/sacrificialjade/sacrificialjade.go
- ui/packages/docs/src/components/Params/weapon_data.json
https://discord.com/channels/845087716541595668/1168674886743490601
- `+params=[stacks=1]` to enable the passive at the beginning of the sim
> add stacks param to sacrificialjade

- pkg/core/player/exec.go
https://discord.com/channels/845087716541595668/1019791863143743509
- does not cover wait, delay and swap
> add back stam_pre and swap_cd_pre on action execution

- pkg/conditional/conditional.go
- ui/packages/docs/docs/reference/fields.md
- ui/packages/docs/docs/reference/system_functions.md
https://discord.com/channels/845087716541595668/1031830118261338152
- add `.previous-char` and `.previous-action` conditionals
- add missing action fields docs (`.action.<action name>`) 
- add missing system func docs (type, execute_action, sin, cos, asin, acos, set_on_tick)
> add conditionals and update gcsl/field docs

- ui/packages/ui/src/Pages/Viewer/Components/Damage/SourceDPSBarChart/BarChart.tsx
- ui/packages/ui/src/Pages/Viewer/Components/Damage/SourceDPSBarChart/index.tsx
https://discord.com/channels/845087716541595668/1131218382671335494
- can either show all or one specific character
All characters:
Specific character:
> add character filter for source dps bar chart

- pkg/agg/failures/failures.go
- pkg/simulator/imports.go
pulling out the simpler changes in #1721 into separate PR
author: @Charlie-Zheng
> fix agg pkg typo

- pkg/optimization/details.go
> update substat optim relevant substats

- ui/packages/embed/src/Layout/Metadata.tsx
adding back dps on embed based on discussion here: https://discord.com/channels/845087716541595668/983391844631212112/1185622407772381254
code is a bit hacky to be maybe fixed if issues comes up
> add back dps on embed

- pkg/core/event/event.go
- pkg/core/player/character/energy.go
sep PR for energy event src type tracking from #1721 
author: @Charlie-Zheng
> energy event to track if src is particle

- ui/packages/docs/src/components/Names/character_data.json
> adjust furina name docs

- ui/packages/ui/src/Sectioning/Nav.tsx
- rename Docs to Documentation in Nav
> Add Releases to Nav

- ui/packages/db/src/SharedComponents/DBEntryView.tsx
- ui/packages/tailwind.config.cjs
- ui/packages/ui/package.json
- ui/packages/ui/src/Pages/Dash/Dash.tsx
- ui/packages/ui/src/Sectioning/Nav.tsx
- ui/packages/ui/src/index.css
- ui/packages/ui/src/index.tsx
- ui/yarn.lock
- adjust navbar responsive design
TODO:
> Add landing page

- internal/characters/neuvillette/asc.go
Updating as per conversation with kolibri.
> fixed neuv a4 to update on HP change

- ui/packages/ui/src/Pages/Dash/Dash.tsx
- ui/packages/ui/src/Sectioning/Nav.tsx
- padding of the two cards (rand sim, release notes) was broken
- add horizontal scroll to latest release on landing page
- fix Navbar on mobile (height, padding)
- fix landing page buttons (padding, rounding)
> fix landing page on mobile

- internal/characters/chongyun/skill.go
- was always 126f regardless of talent level
> fix chongyun a1 and c2 duration

- pkg/reactable/crystallize.go
- pkg/reactable/reactable.go
- 1s cd on triggering crystallize per enemy shared between characters
part of #977
> add crystallize gcd

- internal/characters/gorou/cons.go
- was getting q extension without crystallize
> fix gorou c2 triggering on any shield gain

- internal/artifacts/archaic/archaic.go
- was retriggering on any shield gained while crystallize shield is up
> fix archaic petra trigger

- internal/weapons/sword/swordofnarzissenkreuz/swordofnarzissenkreuz.go
> remove swordofnarzissenkreuz TODO

- internal/characters/furina/asc.go
- internal/characters/furina/attack.go
- internal/characters/furina/charge.go
- ui/packages/docs/src/components/AoE/character_data.json
- remove furina a4 tick rate TODO because info is correct
- fix furina attack hitboxes (normal attack offset, C6-N4 size, remove charge offset TODO)
> adjust furina implementation

- ui/packages/db/src/SharedComponents/DBEntryViewComponents/DBEntryPortrait.tsx
- max-w-32 is not an actual tailwind css class
> fix db entry size on mid size screens

- pkg/core/geometry/rectangle.go
- navia skill was not detecting enemies
> fix point rectangle detection

- ui/packages/ui/src/Pages/Sample/Components/SampleOptions.ts
https://discord.com/channels/845087716541595668/1188923278857875527
> add user to default sample options

- ui/yarn.lock
> update syntax highlighting for charlotte

- pkg/gcs/ast/item.go
- pkg/gcs/ast/keys.go
- pkg/gcs/ast/parseTarget.go
- ui/packages/docs/docs/reference/config.md
this was already half implemented so just finishing it
> add element to threshold particle

- internal/characters/sayu/skill.go
https://discord.com/channels/845087716541595668/1189731995899666563
- 1st DoT should not have elemental DoT
> fix sayu hold e absorb check timing

- internal/characters/shenhe/burst.go
https://discord.com/channels/845087716541595668/1176810603113873468
- blunt but should not shatter
> fix shenhe q initial shattering

- internal/characters/wriothesley/wriothesley.go
- ui/packages/docs/src/components/Fields/character_data.json
- easier to check if enhanced charge attack is available
> add .wriothesley.gracious-rebuke conditional and fix CA stamina consumption always being 0 if below 60% hp

- ui/packages/db/src/Pages/Database/Database.tsx
- ui/packages/ui/src/Pages/Viewer/Components/Miscellaneous/TargetAuraUptimeBarChart/index.tsx
- ui/packages/ui/src/Pages/Viewer/Tabs/Results.tsx
- remove some console.log statements
- don't print received data in DB
- don't print target index array constantly on running sim page
- fix "Empty string passed to getElementById()." warning in running sim page
> Clean up web console output

- .github/actions/deploy-wasm/action.yml
using https://github.com/marketplace/actions/wasm-opt-action
hopefully this works
- no real performance diff
- main.wasm file size reduction of ~22%
> add wasm optimization step for reduced file size

- internal/characters/wriothesley/attack.go
- internal/characters/wriothesley/dash.go
- internal/characters/wriothesley/wriothesley.go
> fix wriothesley na combo resetting on dash/skill

- .github/actions/deploy-wasm/action.yml
> try fixing deployment following wasm optimization

- .github/actions/deploy-wasm/action.yml
> try fixing wasm optimization not finding file

- internal/artifacts/echoes/echoes.go
was broken by me here: https://github.com/genshinsim/gcsim/commit/e9055dee5eb9f3baf6bce8bbe370356beddb63d1
> fix echoes dmg calculation not considering weapon base atk

- internal/characters/alhaitham/plunge.go
- internal/characters/dehya/dehya.go
- internal/characters/kazuha/plunge.go
- internal/characters/tartaglia/aimed.go
- internal/characters/tartaglia/charge.go
- internal/characters/venti/plunge.go
- internal/characters/wanderer/plunge.go
- internal/characters/xiao/plunge.go
- internal/tests/abilities/abil_test.go
> return error instead of idling for invalid action sequences

- pkg/core/combat/hitbox.go
- fix jean self swirl dealing dmg to active char
> adjust SingleTargetHit attack pattern to not include player by default

- internal/artifacts/oceanhuedclam/oceanhuedclam.go
- internal/artifacts/songofdayspast/songofdayspast.go
- pkg/core/core.go
- change core custom flags map value type to float
> fix sodp not considering healing from other set holders

- pkg/reactable/freeze.go
- pkg/reactable/overload.go
- pkg/reactable/reactable.go
- pkg/reactable/superconduct.go
- pkg/reactable/swirl.go
- shatter, overload, superconduct, swirl *element*
closes #977
> add remaining reaction attack gcds

- internal/characters/lisa/skill.go
https://discordapp.com/channels/845087716541595668/1195043083566465074
> fix lisa c1 timing

- pkg/reactable/swirl.go
https://discord.com/channels/845087716541595668/1195991003304308816
- 4f after self swirl
> fix swirl aoe attack delay

- internal/characters/dehya/skill.go
Removed C2 extending initial cast.
C2 extension corrected to 6s.
> Update Dehya C2 Skill Mechanics

- internal/artifacts/songofdayspast/songofdayspast.go
- for checking added dmg in sample
> add artifact log for songofdayspast

- internal/characters/yelan/yelan.go
- ui/packages/docs/src/components/Params/character_data.json
https://discord.com/channels/845087716541595668/1197253656148443247
- adjust docs
> change yelan breakthrough to be enabled at sim start by default

- pkg/simulation/run.go
- improve debugging experience
> print backtrace on simulation panic in CLI

- pkg/core/combat/attack.go
- pkg/enemy/attack.go
- fix damageTaken still counting overkill
- simplify actual dmg calc in applyDamage
- add some more comments clarifying applyDamage
> fix total damage/overall dps counting overkill

- internal/characters/traveler/common/geo/skill.go
- ui/packages/docs/src/components/Params/character_data.json
> add param for travelergeo to not spawn meteorite on skill

- internal/artifacts/emblem/emblem.go
- internal/characters/mona/asc.go
- internal/characters/raiden/asc.go
- internal/characters/raiden/burst.go
- internal/characters/sara/asc.go
- internal/characters/traveler/common/electro/skill.go
- internal/weapons/spear/engulfing/engulfing.go
- pkg/core/player/character/basestat.go
- pkg/core/player/character/energy.go
- pkg/optimization/optstats/energy_stats.go
- done so SnapshotStats are accurate in result proto
- indirectly fix dori a4 not considering base 100% er
- fix substat optimizer energy stat tracking wsum == 0 case using EM instead of ER
> move 100% base er to base stats

- pkg/stats/damage/damage.go
- fix edge case where dmg for iteration is 0
> fix simulation panic in cumulative dmg stat

- ui/packages/ui/src/Pages/Simulator/Toolbox.tsx
- ui/packages/ui/src/Pages/Viewer/Tabs/Config.tsx
- ui/packages/ui/src/Pages/Viewer/UpgradeDialog.tsx
- ui/packages/ui/src/Pages/Viewer/Viewer.tsx
- ui/packages/ui/src/Pages/Viewer/index.tsx
- ui/packages/ui/src/Stores/viewerSlice.ts
- for shared sims / when running from simulator tab
- do not show buttons if no recoveryConfig available
> fix recovery buttons not working

- ui/packages/ui/src/Sectioning/Nav.tsx
- ui/packages/ui/src/Translation/locales/Chinese.json
- ui/packages/ui/src/Translation/locales/English.json
- ui/packages/ui/src/Translation/locales/German.json
- ui/packages/ui/src/Translation/locales/Japanese.json
- ui/packages/ui/src/Translation/locales/Korean.json
- ui/packages/ui/src/Translation/locales/Russian.json
- ui/packages/ui/src/Translation/locales/Spanish.json
- korean lang select should not translate other language options
- delete unused translation keys
> fix nav localization across all supported languages

- ui/packages/db/src/SharedComponents/DBEntryView.tsx
- ui/packages/ui/src/Pages/Dash/Dash.tsx
https://discord.com/channels/845087716541595668/1200438586319831051
> adjust landing page to show description of shown db entry

- internal/characters/alhaitham/skill.go
https://discord.com/channels/845087716541595668/1201362794428248085
- 234f -> 233f
- 214f -> 233f
> fix alhaitham 2nd+ mirror loss timing

- pkg/gcs/ast/lex.go
- pkg/gcs/ast/lex_test.go
fixes `else{` fail to parse properly
> fix ident lex fail with paren

- pkg/core/event/event.go
- pkg/core/player/heal.go
> add OnPlayerPreHPDrain event

- internal/characters/diluc/cons.go
- internal/characters/kaveh/asc.go
- internal/characters/nilou/asc.go
- pkg/avatar/avatar.go
- pkg/core/event/event.go
- fix diluc c2 triggering if someone other than diluc was hit
- fix kaveh a1 triggering if someone other than kaveh was hit
- fix nilou a1 event sub to check for a1 duration on hit char instead of active
> adjust OnPlayerHit to return char hit instead of player struct

- pkg/avatar/avatar.go
- pkg/core/player/heal.go
- account for dehya mitigation in damage log
> adjust drain func to return amount

- internal/characters/keqing/jump.go
- internal/characters/keqing/plunge.go
- pkg/core/player/exec.go
- pkg/core/player/player.go
- pkg/simulation/run.go
preparing for some old bird lady thinggy
> modify airborne check

- pkg/shortcut/weapons.go
- ui/packages/docs/src/components/Names/weapon_data.json
https://discord.com/channels/845087716541595668/1203180626979725332
> add lofi shortcut for lightoffoliarincision

- internal/characters/dehya/skill.go
closes #1977 
- scenario: dehya c2 does skill -> recast skill -> ... -> burst to pick up field -> burst places field -> ... -> skill comes off-cooldown while field still up -> skill used (in bugged version it would go: field status added again -> field status deleted, so recast is unavailable. now it's field status deleted -> field status added again, so recast is available) -> recast
- also: 
- simplify sanctumSavedDur
- remove trailing whitespace in sanctum logs
> fix dehya field pick up timing on off-cooldown skill use when field up

- internal/characters/dehya/burst.go
- c6 max punch count (15) unaffected
> fix dehya burst duration allowing for 11 punches at c0

- internal/characters/chongyun/asc.go
- internal/characters/chongyun/chongyun.go
- internal/characters/chongyun/skill.go
closes #1884 
- also adjust timing for a4 dmg on skill use while field up
> fix chongyun e not working with sac greatsword

- .golangci.yml
- internal/characters/wanderer/burst.go
https://discord.com/channels/845087716541595668/1205238028457607208
> fix wanderer c2 applying to non-windfavored burst

- pkg/simulation/run.go
> fix invalid err when swapping to char doing charge as first action

- cmd/server/main.go
- cmd/wasm/main.go
- go.mod
- go.sum
- pkg/optimization/optstats/simulator.go
- pkg/servermode/handler.go
- pkg/servermode/run.go
- pkg/servermode/server.go
- pkg/servermode/worker.go
- pkg/simulator/simulator.go
- ui/packages/executors/package.json
- ui/packages/executors/src/Executor.ts
- ui/packages/executors/src/ServerExecutor.ts
- ui/packages/executors/src/WasmExecutor.ts
- ui/packages/executors/src/index.ts
- ui/packages/ui/src/Pages/Simulator/Simulator.tsx
- ui/packages/ui/src/Pages/Viewer/Tabs/Config.tsx
- ui/packages/ui/src/Pages/Viewer/UpgradeDialog.tsx
- ui/packages/web/src/App.tsx
- ui/packages/web/src/ServerMode.tsx
- ui/packages/web/src/WasmMode.tsx
- ui/yarn.lock
initial implementation super hacky and buggy but hey it sort of works
> server mode

- internal/artifacts/emblem/emblem.go
- ui/packages/docs/src/components/Names/artifact_data.json
https://discord.com/channels/845087716541595668/1208993243824525332
- esr -> emblem
> fix emblem name docs and status names

- internal/characters/baizhu/skill.go
https://discord.com/channels/845087716541595668/1211399065426985081
- 51f after final hit instead of 3f in single target
> fix baizhu e heal timing

- internal/characters/kazuha/asc.go
- internal/characters/kazuha/burst.go
- internal/characters/lynette/bogglecatbox.go
- internal/characters/sayu/skill.go
- internal/characters/sucrose/burst.go
- internal/characters/traveler/common/anemo/burst.go
- internal/characters/traveler/common/anemo/skill.go
- internal/characters/venti/burst.go
- internal/characters/wanderer/asc.go
- pkg/core/combat/absorb.go
make absorb check show up on the character initiating the check in logs
> add char idx to absorbcheck

- internal/characters/wriothesley/attack.go
- internal/characters/wriothesley/skill.go
- internal/characters/wriothesley/wriothesley.go
> fix wriothesley e buff and aoe increase applying at < 50% hp

- .gitignore
- temporary directory created by Task to store checksums
> add .task directory to gitignore

- internal/artifacts/echoes/echoes.go
- make adding dmg log consistent
- add logs for failing proc due to icd/chance
> adjust echoes 4pc logging

- ui/yarn.lock
> update syntax highlighting for xianyun

- .gitignore
hopefully fix server mode showing unclean msg on sharing
> add release binaries to gitignore

- internal/characters/xianyun/asc.go
- internal/characters/xianyun/burst.go
- happens on same frame as CanQueueAfter now
> fix xianyun q stack reduction timing

- internal/characters/barbara/plunge.go
- internal/characters/klee/plunge.go
- internal/characters/sucrose/plunge.go
- internal/characters/xianyun/plunge.go
- barbara, klee, sucrose
- also: use hitmark for xianyun's own lp/hp -> dash frames
> fix some xianyun plunge frames to avoid CanQueueAfter issues

- internal/weapons/bow/alley/alley.go
> fix alley hunter stopping stacking if swapping between two non-holder characters

- go.mod
> Revert "bump mod to v2"

- ui/packages/components/src/Cards/CardBadge/CardBadge.tsx
- ui/packages/components/src/Cards/DBCard/DBCard.tsx
- ui/packages/components/src/common/ui/badge.tsx
> update db card styling

- ui/packages/components/src/Cards/DBCard/DBCard.tsx
- ui/packages/storybook/src/stories/DBCard.stories.tsx
> fix db card stretching

- ui/packages/localization/src/locales/German.json
> add german to db translations

- ui/packages/localization/src/locales/Spanish.json
> add spanish translation for db

- internal/characters/ayato/charge.go
- ui/packages/docs/src/components/Actions/character_data.json
> Illegalize ayato ca in skill state

- internal/weapons/sword/haran/haran.go
Haran should not override the buff if there are no stacks.
no stacks: https://streamable.com/e9okjl
at least one stack: https://streamable.com/ohujzl
> fix haran onskill

- internal/characters/beidou/skill.go
beidou's tap skill applies shield
evidence; https://www.youtube.com/watch?v=o4_VTkj1S0g
> apply beidou shield on skill tap

- internal/characters/furina/furina.go
- internal/characters/heizou/heizou.go
- internal/characters/tartaglia/tartaglia.go
- internal/characters/wriothesley/wriothesley.go
- internal/template/character/character.go
- pkg/core/player/character/character.go
- pkg/gcs/sysfunc.go
- pkg/simulation/run.go
- pkg/testhelper/character.go
allows for char to also block swap if swap is not a valid next action
> NextQueueItemIsValid to use active char instead of next char

- ui/packages/db/src/Pages/Database/Database.tsx
Added feature that cancel previous requests if new was run
> Previous DB requests cancellation

- ui/packages/db/src/SharedHooks/databaseQuery.ts
Allow sorting when using custom queries
> Allow the sorting configurations still apply to the custom filter

- internal/characters/emilie/asc.go
- internal/characters/emilie/attack.go
- internal/characters/emilie/burst.go
- internal/characters/emilie/charge.go
- internal/characters/emilie/cons.go
- internal/characters/emilie/emilie.go
- internal/characters/emilie/lumidouce.go
- internal/characters/emilie/skill.go
- [add cooldown and scent generation for c6](https://github.com/genshinsim/gcsim/commit/1b5df8e569addd5c3aa83aba4d1ede71fddd0bb0)
- [rework spawning lumidouce case and consuming scents](https://github.com/genshinsim/gcsim/commit/b3b52666785270ce0786ce17528981a4806b0565)
> emilie bugfixes

- internal/characters/wriothesley/cons.go
> Fix Wrio C6 applying at C1

- internal/weapons/catalyst/frostbearer/frostbearer.go
- internal/weapons/claymore/prototype/prototype.go
> fix couple typos

- internal/weapons/catalyst/ashgraven/ashgraven.go
> fix ashgraven damage

- internal/characters/furina/asc.go
- internal/characters/furina/furina.go
> Fixed furina a1 being able to be double queued

- internal/characters/mualani/attack.go
- internal/characters/mualani/burst.go
- internal/characters/mualani/dash.go
- internal/characters/mualani/jump.go
- internal/characters/mualani/skill.go
- internal/characters/mualani/walk.go
Adjusted skill state to start immediately. Adjusted momentum gain to only occur if moving
> Mualani bugfixes

- internal/characters/mualani/skill.go
usage: `mualani walk, skill, walk`
> allow use mualani skill while walking

- internal/artifacts/flowerofparadiselost/flowerofparadiselost.go
- internal/artifacts/thunderingfury/thunderingfury.go
- internal/characters/chevreuse/skill.go
- internal/characters/collei/asc.go
- internal/characters/collei/collei.go
- internal/characters/collei/cons.go
- internal/characters/cyno/cons.go
- internal/characters/dori/asc.go
- internal/characters/fischl/asc.go
- internal/characters/freminet/asc.go
- internal/characters/freminet/cons.go
- internal/characters/kazuha/asc.go
- internal/characters/keqing/cons.go
- internal/characters/neuvillette/asc.go
- internal/characters/sayu/asc.go
- internal/characters/sucrose/asc.go
- internal/characters/tighnari/cons.go
- internal/characters/yunjin/cons.go
- internal/weapons/catalyst/emeraldorb/emeraldorb.go
- internal/weapons/catalyst/hakushin/hakushin.go
- internal/weapons/claymore/earthshaker/earthshaker.go
- internal/weapons/claymore/forestregalia/forestregalia.go
- internal/weapons/spear/moonpiercer/moonpiercer.go
- internal/weapons/sword/darkironsword/darkironsword.go
- internal/weapons/sword/sapwoodblade/sapwoodblade.go
- pkg/simulation/setup.go
- Fix sucrose a1 triggering on guoba swirl
> Fix gadget checks

- scripts/dbcompare/main.go
example:
```
go run . --must=neuvillette,furina --iters=100 --workers=10
```
output
```
id,original,next,diff,abs_diff,err
neuvillette+furina+zhongli+kazuha,zF6TMQtr9Pbm,82504.37366957322,82688.07757090023,183.7039013270114,183.7039013270114,<nil>
neuvillette+furina+nahida+xiangling,hznTjMTPkzgD,84714.19188640836,84733.41701752147,19.225131113111274,19.225131113111274,<nil>
neuvillette+furina+nahida+raiden,pzhj6TDkwtfg,86594.20556945758,86784.86559437338,190.66002491579275,190.66002491579275,<nil>
neuvillette+furina+zhongli+sayu,cqnMfMzHDJCk,77118.59434623182,77084.71755695663,-33.876789275193005,33.876789275193005,<nil>
etc...
```
> add some cmd line param to dbcompare

- cmd/gcsim/main.go
I'm sorry I have no idea how to fix the Lint error so i'm trying different things. This time I edited the code directly on the github website. I wonder if it'll still complain and if it's something to do with the code itself.
> Allow -out option to work with serve

- internal/weapons/claymore/pines/pines.go
Attack speed should apply only to normal attacks
> fix song of broken pines atk speed

- internal/characters/nilou/bountifulcore.go
- pkg/reactable/bloom.go
Fixes a bug with fopl and gilded where the first reaction doesn't benefit from 4p bonus.
> Change blooms to calc dmg at hitmark frame

- internal/characters/xinyan/burst.go
- internal/characters/xinyan/cons.go
- internal/characters/xinyan/skill.go
- ui/packages/docs/src/components/Frames/character_data.json
1. only physical damage gets guaranteed crit
2. added extra C2 pulses from https://library.keqingmains.com/evidence/characters/pyro/xinyan#xinyan-c2-shield-formation-pulses-extra-times, they were already in the original frame recording just uncounted.
> fix xinyan c2

- internal/characters/cyno/charge.go
fix cyno burst CA being able to infuse
> fix cyno burst CA being able to infuse

- pkg/core/player/player.go
- pkg/gcs/sysfunc.go
- ui/packages/docs/docs/reference/system_functions.md
https://discord.com/channels/763583452762734592/851428030094114847/1350265728065994893
> Add swap ICD change to simulate booking

- internal/weapons/bow/chainbreaker/chainbreaker.go
By testing, although the description of the weapon does not explicitly specify, the maximum attack buff stack is 3.
> Fix Chain Breaker's Flower—Feather Song: max atk stack is 3

- ui/packages/workers/src/assets/index.ts
- ui/packages/workers/src/preview/handlePreview.ts
previous PR didn't do anything because it was on preview endpoint, not assets..
> don't cache on assets not found

- internal/characters/ayato/ayato.go
- internal/characters/ayato/cons.go
> change ayato c6 to not be affected by namisen

- pkg/gcs/eval.go
- pkg/gcs/eval_fn_test.go
- pkg/gcs/eval_test.go
- pkg/gcs/function.go
- pkg/gcs/op.go
- pkg/gcs/sysfunc.go
also fixed error handling in `set_on_tick`
> add validateArgument to simplify the sysfunc code

- internal/characters/xingqiu/attack.go
N3>C and N3>N4 cancel frames were swapped
> fix xingqiu N3 cancel frames

- internal/characters/escoffier/cons.go
we test in production
was missing cryo check and attacktag check
also logging fix, decrement counter before outputting the remaining count
> fix escoffier c2

- internal/characters/varesa/asc.go
- internal/characters/varesa/burst.go
- internal/characters/varesa/plunge.go
- internal/characters/varesa/varesa.go
- internal/weapons/catalyst/vividnotions/vividnotions.go
- ui/packages/docs/src/components/Actions/character_data.json
- added action data on documentation for varesa;
- fixed 28% cd buff of vivid for varesa mini burst;
- fixed varesa a1 buff for varesa mini burst.
> varesa fixes

- internal/characters/traveler/common/pyro/asc.go
change pmc a4 icd from 12 frames to 12 seconds
> Fix PMC A4 ICD

- scripts/dbcompare/main.go
> additional warn column for dbcompare based on percentage
